item {
 id: 1
 name: "backpack"
}
item {
 id: 2
 name: "survivor"
}
item {
 id: 3
 name: "phone"
}
item {
 id: 4
 name: "rope"
}
item {
 id: 5
 name: "helmet"
}
item {
 id: 6
 name: "robot"
}
