dist: bionic
language: python
os:
    - linux
    - window
python:
    - "3.6"
    - "3.7"
script:
    - python -m unittest discover --top-level-directory . --start-directory subt
    - python -m unittest discover --top-level-directory . --start-directory osgar
branches:
  only:
    - master
