[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
# A Black (https://github.com/psf/black)-compatible isort
# (https://timothycrosley.github.io/isort/) config. Copy-pasted from Black's
# README.
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
