# metadata
run_name: 'playground'
# characteristic number for map
perf_num: 7

# map paths
map_path: './configs/example_map2'
map_ext: '.png'

# starting pose for map
sx: 0.0
sy: 0.0
stheta: 3.1415


# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345
