# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/actor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import entity_pb2 as ignition_dot_msgs_dot_entity__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/actor.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x19ignition/msgs/actor.proto\x12\rignition.msgs\x1a\x1aignition/msgs/entity.proto\x1a\x1aignition/msgs/header.proto\x1a\x18ignition/msgs/pose.proto\"\xfc\x04\n\x05\x41\x63tor\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12%\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x15.ignition.msgs.Entity\x12!\n\x04pose\x18\x03 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12\x15\n\rskin_filename\x18\x04 \x01(\t\x12\x12\n\nskin_scale\x18\x05 \x01(\x02\x12\x32\n\nanimations\x18\x06 \x03(\x0b\x32\x1e.ignition.msgs.Actor.Animation\x12\x13\n\x0bscript_loop\x18\x07 \x01(\x08\x12\x1a\n\x12script_delay_start\x18\x08 \x01(\x02\x12\x19\n\x11script_auto_start\x18\t \x01(\x08\x12\x35\n\x0ctrajectories\x18\n \x03(\x0b\x32\x1f.ignition.msgs.Actor.Trajectory\x12%\n\x06parent\x18\x0b \x01(\x0b\x32\x15.ignition.msgs.Entity\x1aQ\n\tAnimation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\r\n\x05scale\x18\x03 \x01(\x02\x12\x15\n\rinterpolate_x\x18\x04 \x01(\x08\x1a;\n\x08Waypoint\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12!\n\x04pose\x18\x02 \x01(\x0b\x32\x13.ignition.msgs.Pose\x1ai\n\nTrajectory\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07tension\x18\x03 \x01(\x02\x12\x30\n\twaypoints\x18\x04 \x03(\x0b\x32\x1d.ignition.msgs.Actor.WaypointB \n\x11\x63om.ignition.msgsB\x0b\x41\x63torProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_entity__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTOR_ANIMATION = _descriptor.Descriptor(
  name='Animation',
  full_name='ignition.msgs.Actor.Animation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Actor.Animation.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='ignition.msgs.Actor.Animation.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='ignition.msgs.Actor.Animation.scale', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interpolate_x', full_name='ignition.msgs.Actor.Animation.interpolate_x', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=595,
)

_ACTOR_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='ignition.msgs.Actor.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ignition.msgs.Actor.Waypoint.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Actor.Waypoint.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=656,
)

_ACTOR_TRAJECTORY = _descriptor.Descriptor(
  name='Trajectory',
  full_name='ignition.msgs.Actor.Trajectory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.Actor.Trajectory.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Actor.Trajectory.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tension', full_name='ignition.msgs.Actor.Trajectory.tension', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='ignition.msgs.Actor.Trajectory.waypoints', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=763,
)

_ACTOR = _descriptor.Descriptor(
  name='Actor',
  full_name='ignition.msgs.Actor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Actor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity', full_name='ignition.msgs.Actor.entity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Actor.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skin_filename', full_name='ignition.msgs.Actor.skin_filename', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skin_scale', full_name='ignition.msgs.Actor.skin_scale', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='animations', full_name='ignition.msgs.Actor.animations', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='script_loop', full_name='ignition.msgs.Actor.script_loop', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='script_delay_start', full_name='ignition.msgs.Actor.script_delay_start', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='script_auto_start', full_name='ignition.msgs.Actor.script_auto_start', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trajectories', full_name='ignition.msgs.Actor.trajectories', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='ignition.msgs.Actor.parent', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTOR_ANIMATION, _ACTOR_WAYPOINT, _ACTOR_TRAJECTORY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=763,
)

_ACTOR_ANIMATION.containing_type = _ACTOR
_ACTOR_WAYPOINT.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_ACTOR_WAYPOINT.containing_type = _ACTOR
_ACTOR_TRAJECTORY.fields_by_name['waypoints'].message_type = _ACTOR_WAYPOINT
_ACTOR_TRAJECTORY.containing_type = _ACTOR
_ACTOR.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_ACTOR.fields_by_name['entity'].message_type = ignition_dot_msgs_dot_entity__pb2._ENTITY
_ACTOR.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_ACTOR.fields_by_name['animations'].message_type = _ACTOR_ANIMATION
_ACTOR.fields_by_name['trajectories'].message_type = _ACTOR_TRAJECTORY
_ACTOR.fields_by_name['parent'].message_type = ignition_dot_msgs_dot_entity__pb2._ENTITY
DESCRIPTOR.message_types_by_name['Actor'] = _ACTOR

Actor = _reflection.GeneratedProtocolMessageType('Actor', (_message.Message,), dict(

  Animation = _reflection.GeneratedProtocolMessageType('Animation', (_message.Message,), dict(
    DESCRIPTOR = _ACTOR_ANIMATION,
    __module__ = 'ignition.msgs.actor_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.Actor.Animation)
    ))
  ,

  Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), dict(
    DESCRIPTOR = _ACTOR_WAYPOINT,
    __module__ = 'ignition.msgs.actor_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.Actor.Waypoint)
    ))
  ,

  Trajectory = _reflection.GeneratedProtocolMessageType('Trajectory', (_message.Message,), dict(
    DESCRIPTOR = _ACTOR_TRAJECTORY,
    __module__ = 'ignition.msgs.actor_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.Actor.Trajectory)
    ))
  ,
  DESCRIPTOR = _ACTOR,
  __module__ = 'ignition.msgs.actor_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Actor)
  ))
_sym_db.RegisterMessage(Actor)
_sym_db.RegisterMessage(Actor.Animation)
_sym_db.RegisterMessage(Actor.Waypoint)
_sym_db.RegisterMessage(Actor.Trajectory)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\013ActorProtos'))
# @@protoc_insertion_point(module_scope)
