# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/axis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/axis.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x18ignition/msgs/axis.proto\x12\rignition.msgs\x1a\x1cignition/msgs/vector3d.proto\x1a\x1aignition/msgs/header.proto\"\xd5\x02\n\x04\x41xis\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12$\n\x03xyz\x18\x02 \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12\x13\n\x0blimit_lower\x18\x03 \x01(\x01\x12\x13\n\x0blimit_upper\x18\x04 \x01(\x01\x12\x14\n\x0climit_effort\x18\x05 \x01(\x01\x12\x16\n\x0elimit_velocity\x18\x06 \x01(\x01\x12\x0f\n\x07\x64\x61mping\x18\x07 \x01(\x01\x12\x10\n\x08\x66riction\x18\x08 \x01(\x01\x12\"\n\x16use_parent_model_frame\x18\t \x01(\x08\x42\x02\x18\x01\x12\x10\n\x08position\x18\n \x01(\x01\x12\x10\n\x08velocity\x18\x0b \x01(\x01\x12\r\n\x05\x66orce\x18\x0c \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\r \x01(\x01\x12\x18\n\x10xyz_expressed_in\x18\x0e \x01(\tB\x1f\n\x11\x63om.ignition.msgsB\nAxisProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AXIS = _descriptor.Descriptor(
  name='Axis',
  full_name='ignition.msgs.Axis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Axis.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xyz', full_name='ignition.msgs.Axis.xyz', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_lower', full_name='ignition.msgs.Axis.limit_lower', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_upper', full_name='ignition.msgs.Axis.limit_upper', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_effort', full_name='ignition.msgs.Axis.limit_effort', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_velocity', full_name='ignition.msgs.Axis.limit_velocity', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='damping', full_name='ignition.msgs.Axis.damping', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friction', full_name='ignition.msgs.Axis.friction', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_parent_model_frame', full_name='ignition.msgs.Axis.use_parent_model_frame', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='position', full_name='ignition.msgs.Axis.position', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='ignition.msgs.Axis.velocity', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='force', full_name='ignition.msgs.Axis.force', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='ignition.msgs.Axis.acceleration', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xyz_expressed_in', full_name='ignition.msgs.Axis.xyz_expressed_in', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=443,
)

_AXIS.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_AXIS.fields_by_name['xyz'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Axis'] = _AXIS

Axis = _reflection.GeneratedProtocolMessageType('Axis', (_message.Message,), dict(
  DESCRIPTOR = _AXIS,
  __module__ = 'ignition.msgs.axis_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Axis)
  ))
_sym_db.RegisterMessage(Axis)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\nAxisProtos'))
_AXIS.fields_by_name['use_parent_model_frame'].has_options = True
_AXIS.fields_by_name['use_parent_model_frame']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
# @@protoc_insertion_point(module_scope)
