# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/boolean.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/boolean.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1bignition/msgs/boolean.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\">\n\x07\x42oolean\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x08\x42\x1f\n\x11\x63om.ignition.msgsB\nBoolProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BOOLEAN = _descriptor.Descriptor(
  name='Boolean',
  full_name='ignition.msgs.Boolean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Boolean.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ignition.msgs.Boolean.data', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=136,
)

_BOOLEAN.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['Boolean'] = _BOOLEAN

Boolean = _reflection.GeneratedProtocolMessageType('Boolean', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEAN,
  __module__ = 'ignition.msgs.boolean_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Boolean)
  ))
_sym_db.RegisterMessage(Boolean)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\nBoolProtos'))
# @@protoc_insertion_point(module_scope)
