# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/boxgeom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/boxgeom.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1bignition/msgs/boxgeom.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\x1a\x1cignition/msgs/vector3d.proto\"W\n\x07\x42oxGeom\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12%\n\x04size\x18\x02 \x01(\x0b\x32\x17.ignition.msgs.Vector3dB\"\n\x11\x63om.ignition.msgsB\rBoxGeomProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BOXGEOM = _descriptor.Descriptor(
  name='BoxGeom',
  full_name='ignition.msgs.BoxGeom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.BoxGeom.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='ignition.msgs.BoxGeom.size', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=191,
)

_BOXGEOM.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_BOXGEOM.fields_by_name['size'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['BoxGeom'] = _BOXGEOM

BoxGeom = _reflection.GeneratedProtocolMessageType('BoxGeom', (_message.Message,), dict(
  DESCRIPTOR = _BOXGEOM,
  __module__ = 'ignition.msgs.boxgeom_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.BoxGeom)
  ))
_sym_db.RegisterMessage(BoxGeom)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\rBoxGeomProtos'))
# @@protoc_insertion_point(module_scope)
