# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/camera_lens.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/camera_lens.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1fignition/msgs/camera_lens.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\"\xd2\x01\n\nCameraLens\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02\x63\x31\x18\x03 \x01(\x01\x12\n\n\x02\x63\x32\x18\x04 \x01(\x01\x12\n\n\x02\x63\x33\x18\x05 \x01(\x01\x12\t\n\x01\x66\x18\x06 \x01(\x01\x12\x0b\n\x03\x66un\x18\x07 \x01(\t\x12\x15\n\rscale_to_hfov\x18\x08 \x01(\x08\x12\x14\n\x0c\x63utoff_angle\x18\t \x01(\x01\x12\x0c\n\x04hfov\x18\n \x01(\x01\x12\x18\n\x10\x65nv_texture_size\x18\x0b \x01(\x05\x42%\n\x11\x63om.ignition.msgsB\x10\x43\x61meraLensProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAMERALENS = _descriptor.Descriptor(
  name='CameraLens',
  full_name='ignition.msgs.CameraLens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.CameraLens.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.CameraLens.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c1', full_name='ignition.msgs.CameraLens.c1', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c2', full_name='ignition.msgs.CameraLens.c2', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c3', full_name='ignition.msgs.CameraLens.c3', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='ignition.msgs.CameraLens.f', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fun', full_name='ignition.msgs.CameraLens.fun', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale_to_hfov', full_name='ignition.msgs.CameraLens.scale_to_hfov', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cutoff_angle', full_name='ignition.msgs.CameraLens.cutoff_angle', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hfov', full_name='ignition.msgs.CameraLens.hfov', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='env_texture_size', full_name='ignition.msgs.CameraLens.env_texture_size', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=289,
)

_CAMERALENS.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['CameraLens'] = _CAMERALENS

CameraLens = _reflection.GeneratedProtocolMessageType('CameraLens', (_message.Message,), dict(
  DESCRIPTOR = _CAMERALENS,
  __module__ = 'ignition.msgs.camera_lens_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.CameraLens)
  ))
_sym_db.RegisterMessage(CameraLens)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\020CameraLensProtos'))
# @@protoc_insertion_point(module_scope)
