# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/camerasensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import vector2d_pb2 as ignition_dot_msgs_dot_vector2d__pb2
from ignition.msgs import distortion_pb2 as ignition_dot_msgs_dot_distortion__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/camerasensor.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n ignition/msgs/camerasensor.proto\x12\rignition.msgs\x1a\x1cignition/msgs/vector2d.proto\x1a\x1eignition/msgs/distortion.proto\x1a\x1aignition/msgs/header.proto\"\x8d\x02\n\x0c\x43\x61meraSensor\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x16\n\x0ehorizontal_fov\x18\x02 \x01(\x01\x12+\n\nimage_size\x18\x03 \x01(\x0b\x32\x17.ignition.msgs.Vector2d\x12\x14\n\x0cimage_format\x18\x04 \x01(\t\x12\x11\n\tnear_clip\x18\x05 \x01(\x01\x12\x10\n\x08\x66\x61r_clip\x18\x06 \x01(\x01\x12\x14\n\x0csave_enabled\x18\x07 \x01(\x08\x12\x11\n\tsave_path\x18\x08 \x01(\t\x12-\n\ndistortion\x18\t \x01(\x0b\x32\x19.ignition.msgs.DistortionB\'\n\x11\x63om.ignition.msgsB\x12\x43\x61meraSensorProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_vector2d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_distortion__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAMERASENSOR = _descriptor.Descriptor(
  name='CameraSensor',
  full_name='ignition.msgs.CameraSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.CameraSensor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='horizontal_fov', full_name='ignition.msgs.CameraSensor.horizontal_fov', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_size', full_name='ignition.msgs.CameraSensor.image_size', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_format', full_name='ignition.msgs.CameraSensor.image_format', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='near_clip', full_name='ignition.msgs.CameraSensor.near_clip', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='far_clip', full_name='ignition.msgs.CameraSensor.far_clip', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_enabled', full_name='ignition.msgs.CameraSensor.save_enabled', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_path', full_name='ignition.msgs.CameraSensor.save_path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distortion', full_name='ignition.msgs.CameraSensor.distortion', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=411,
)

_CAMERASENSOR.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_CAMERASENSOR.fields_by_name['image_size'].message_type = ignition_dot_msgs_dot_vector2d__pb2._VECTOR2D
_CAMERASENSOR.fields_by_name['distortion'].message_type = ignition_dot_msgs_dot_distortion__pb2._DISTORTION
DESCRIPTOR.message_types_by_name['CameraSensor'] = _CAMERASENSOR

CameraSensor = _reflection.GeneratedProtocolMessageType('CameraSensor', (_message.Message,), dict(
  DESCRIPTOR = _CAMERASENSOR,
  __module__ = 'ignition.msgs.camerasensor_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.CameraSensor)
  ))
_sym_db.RegisterMessage(CameraSensor)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\022CameraSensorProtos'))
# @@protoc_insertion_point(module_scope)
