# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/camera_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/camera_info.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1fignition/msgs/camera_info.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\"\x87\x04\n\nCameraInfo\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x38\n\ndistortion\x18\x04 \x01(\x0b\x32$.ignition.msgs.CameraInfo.Distortion\x12\x38\n\nintrinsics\x18\x05 \x01(\x0b\x32$.ignition.msgs.CameraInfo.Intrinsics\x12\x38\n\nprojection\x18\x06 \x01(\x0b\x32$.ignition.msgs.CameraInfo.Projection\x12 \n\x14rectification_matrix\x18\x07 \x03(\x01\x42\x02\x10\x01\x1a\xb0\x01\n\nDistortion\x12G\n\x05model\x18\x01 \x01(\x0e\x32\x38.ignition.msgs.CameraInfo.Distortion.DistortionModelType\x12\t\n\x01k\x18\x02 \x03(\x01\"N\n\x13\x44istortionModelType\x12\r\n\tPLUMB_BOB\x10\x00\x12\x17\n\x13RATIONAL_POLYNOMIAL\x10\x01\x12\x0f\n\x0b\x45QUIDISTANT\x10\x02\x1a\x17\n\nIntrinsics\x12\t\n\x01k\x18\x01 \x03(\x01\x1a\x17\n\nProjection\x12\t\n\x01p\x18\x01 \x03(\x01\x42%\n\x11\x63om.ignition.msgsB\x10\x43\x61meraInfoProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CAMERAINFO_DISTORTION_DISTORTIONMODELTYPE = _descriptor.EnumDescriptor(
  name='DistortionModelType',
  full_name='ignition.msgs.CameraInfo.Distortion.DistortionModelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLUMB_BOB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RATIONAL_POLYNOMIAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUIDISTANT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=470,
  serialized_end=548,
)
_sym_db.RegisterEnumDescriptor(_CAMERAINFO_DISTORTION_DISTORTIONMODELTYPE)


_CAMERAINFO_DISTORTION = _descriptor.Descriptor(
  name='Distortion',
  full_name='ignition.msgs.CameraInfo.Distortion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='ignition.msgs.CameraInfo.Distortion.model', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k', full_name='ignition.msgs.CameraInfo.Distortion.k', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CAMERAINFO_DISTORTION_DISTORTIONMODELTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=548,
)

_CAMERAINFO_INTRINSICS = _descriptor.Descriptor(
  name='Intrinsics',
  full_name='ignition.msgs.CameraInfo.Intrinsics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k', full_name='ignition.msgs.CameraInfo.Intrinsics.k', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=573,
)

_CAMERAINFO_PROJECTION = _descriptor.Descriptor(
  name='Projection',
  full_name='ignition.msgs.CameraInfo.Projection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='ignition.msgs.CameraInfo.Projection.p', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=598,
)

_CAMERAINFO = _descriptor.Descriptor(
  name='CameraInfo',
  full_name='ignition.msgs.CameraInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.CameraInfo.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='ignition.msgs.CameraInfo.width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='ignition.msgs.CameraInfo.height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distortion', full_name='ignition.msgs.CameraInfo.distortion', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intrinsics', full_name='ignition.msgs.CameraInfo.intrinsics', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projection', full_name='ignition.msgs.CameraInfo.projection', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rectification_matrix', full_name='ignition.msgs.CameraInfo.rectification_matrix', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[_CAMERAINFO_DISTORTION, _CAMERAINFO_INTRINSICS, _CAMERAINFO_PROJECTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=598,
)

_CAMERAINFO_DISTORTION.fields_by_name['model'].enum_type = _CAMERAINFO_DISTORTION_DISTORTIONMODELTYPE
_CAMERAINFO_DISTORTION.containing_type = _CAMERAINFO
_CAMERAINFO_DISTORTION_DISTORTIONMODELTYPE.containing_type = _CAMERAINFO_DISTORTION
_CAMERAINFO_INTRINSICS.containing_type = _CAMERAINFO
_CAMERAINFO_PROJECTION.containing_type = _CAMERAINFO
_CAMERAINFO.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_CAMERAINFO.fields_by_name['distortion'].message_type = _CAMERAINFO_DISTORTION
_CAMERAINFO.fields_by_name['intrinsics'].message_type = _CAMERAINFO_INTRINSICS
_CAMERAINFO.fields_by_name['projection'].message_type = _CAMERAINFO_PROJECTION
DESCRIPTOR.message_types_by_name['CameraInfo'] = _CAMERAINFO

CameraInfo = _reflection.GeneratedProtocolMessageType('CameraInfo', (_message.Message,), dict(

  Distortion = _reflection.GeneratedProtocolMessageType('Distortion', (_message.Message,), dict(
    DESCRIPTOR = _CAMERAINFO_DISTORTION,
    __module__ = 'ignition.msgs.camera_info_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.CameraInfo.Distortion)
    ))
  ,

  Intrinsics = _reflection.GeneratedProtocolMessageType('Intrinsics', (_message.Message,), dict(
    DESCRIPTOR = _CAMERAINFO_INTRINSICS,
    __module__ = 'ignition.msgs.camera_info_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.CameraInfo.Intrinsics)
    ))
  ,

  Projection = _reflection.GeneratedProtocolMessageType('Projection', (_message.Message,), dict(
    DESCRIPTOR = _CAMERAINFO_PROJECTION,
    __module__ = 'ignition.msgs.camera_info_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.CameraInfo.Projection)
    ))
  ,
  DESCRIPTOR = _CAMERAINFO,
  __module__ = 'ignition.msgs.camera_info_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.CameraInfo)
  ))
_sym_db.RegisterMessage(CameraInfo)
_sym_db.RegisterMessage(CameraInfo.Distortion)
_sym_db.RegisterMessage(CameraInfo.Intrinsics)
_sym_db.RegisterMessage(CameraInfo.Projection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\020CameraInfoProtos'))
_CAMERAINFO.fields_by_name['rectification_matrix'].has_options = True
_CAMERAINFO.fields_by_name['rectification_matrix']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
