# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/cmd_vel2d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/cmd_vel2d.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1dignition/msgs/cmd_vel2d.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\"R\n\x08\x43mdVel2D\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x10\n\x08velocity\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\x42#\n\x11\x63om.ignition.msgsB\x0e\x43mdVel2DProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CMDVEL2D = _descriptor.Descriptor(
  name='CmdVel2D',
  full_name='ignition.msgs.CmdVel2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.CmdVel2D.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='ignition.msgs.CmdVel2D.velocity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta', full_name='ignition.msgs.CmdVel2D.theta', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=158,
)

_CMDVEL2D.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['CmdVel2D'] = _CMDVEL2D

CmdVel2D = _reflection.GeneratedProtocolMessageType('CmdVel2D', (_message.Message,), dict(
  DESCRIPTOR = _CMDVEL2D,
  __module__ = 'ignition.msgs.cmd_vel2d_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.CmdVel2D)
  ))
_sym_db.RegisterMessage(CmdVel2D)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\016CmdVel2DProtos'))
# @@protoc_insertion_point(module_scope)
