# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/collision.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import geometry_pb2 as ignition_dot_msgs_dot_geometry__pb2
from ignition.msgs import surface_pb2 as ignition_dot_msgs_dot_surface__pb2
from ignition.msgs import visual_pb2 as ignition_dot_msgs_dot_visual__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/collision.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1dignition/msgs/collision.proto\x12\rignition.msgs\x1a\x18ignition/msgs/pose.proto\x1a\x1cignition/msgs/geometry.proto\x1a\x1bignition/msgs/surface.proto\x1a\x1aignition/msgs/visual.proto\x1a\x1aignition/msgs/header.proto\"\x95\x02\n\tCollision\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0blaser_retro\x18\x04 \x01(\x01\x12\x14\n\x0cmax_contacts\x18\x05 \x01(\x01\x12!\n\x04pose\x18\x06 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12)\n\x08geometry\x18\x07 \x01(\x0b\x32\x17.ignition.msgs.Geometry\x12\'\n\x07surface\x18\x08 \x01(\x0b\x32\x16.ignition.msgs.Surface\x12%\n\x06visual\x18\t \x03(\x0b\x32\x15.ignition.msgs.VisualB$\n\x11\x63om.ignition.msgsB\x0f\x43ollisionProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_geometry__pb2.DESCRIPTOR,ignition_dot_msgs_dot_surface__pb2.DESCRIPTOR,ignition_dot_msgs_dot_visual__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COLLISION = _descriptor.Descriptor(
  name='Collision',
  full_name='ignition.msgs.Collision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Collision.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.Collision.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Collision.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laser_retro', full_name='ignition.msgs.Collision.laser_retro', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_contacts', full_name='ignition.msgs.Collision.max_contacts', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Collision.pose', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='ignition.msgs.Collision.geometry', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='surface', full_name='ignition.msgs.Collision.surface', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visual', full_name='ignition.msgs.Collision.visual', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=467,
)

_COLLISION.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_COLLISION.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_COLLISION.fields_by_name['geometry'].message_type = ignition_dot_msgs_dot_geometry__pb2._GEOMETRY
_COLLISION.fields_by_name['surface'].message_type = ignition_dot_msgs_dot_surface__pb2._SURFACE
_COLLISION.fields_by_name['visual'].message_type = ignition_dot_msgs_dot_visual__pb2._VISUAL
DESCRIPTOR.message_types_by_name['Collision'] = _COLLISION

Collision = _reflection.GeneratedProtocolMessageType('Collision', (_message.Message,), dict(
  DESCRIPTOR = _COLLISION,
  __module__ = 'ignition.msgs.collision_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Collision)
  ))
_sym_db.RegisterMessage(Collision)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\017CollisionProtos'))
# @@protoc_insertion_point(module_scope)
