# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/contacts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import contact_pb2 as ignition_dot_msgs_dot_contact__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/contacts.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1cignition/msgs/contacts.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\x1a\x1bignition/msgs/contact.proto\"Z\n\x08\x43ontacts\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\'\n\x07\x63ontact\x18\x02 \x03(\x0b\x32\x16.ignition.msgs.ContactB#\n\x11\x63om.ignition.msgsB\x0e\x43ontactsProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_contact__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTACTS = _descriptor.Descriptor(
  name='Contacts',
  full_name='ignition.msgs.Contacts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Contacts.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contact', full_name='ignition.msgs.Contacts.contact', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=194,
)

_CONTACTS.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_CONTACTS.fields_by_name['contact'].message_type = ignition_dot_msgs_dot_contact__pb2._CONTACT
DESCRIPTOR.message_types_by_name['Contacts'] = _CONTACTS

Contacts = _reflection.GeneratedProtocolMessageType('Contacts', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTS,
  __module__ = 'ignition.msgs.contacts_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Contacts)
  ))
_sym_db.RegisterMessage(Contacts)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\016ContactsProtos'))
# @@protoc_insertion_point(module_scope)
