# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/contact.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import entity_pb2 as ignition_dot_msgs_dot_entity__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import joint_wrench_pb2 as ignition_dot_msgs_dot_joint__wrench__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/contact.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1bignition/msgs/contact.proto\x12\rignition.msgs\x1a\x1aignition/msgs/entity.proto\x1a\x1cignition/msgs/vector3d.proto\x1a ignition/msgs/joint_wrench.proto\x1a\x1aignition/msgs/header.proto\"\xbb\x02\n\x07\x43ontact\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12)\n\ncollision1\x18\x02 \x01(\x0b\x32\x15.ignition.msgs.Entity\x12)\n\ncollision2\x18\x03 \x01(\x0b\x32\x15.ignition.msgs.Entity\x12)\n\x08position\x18\x04 \x03(\x0b\x32\x17.ignition.msgs.Vector3d\x12\'\n\x06normal\x18\x05 \x03(\x0b\x32\x17.ignition.msgs.Vector3d\x12\r\n\x05\x64\x65pth\x18\x06 \x03(\x01\x12*\n\x06wrench\x18\x07 \x03(\x0b\x32\x1a.ignition.msgs.JointWrench\x12$\n\x05world\x18\x08 \x01(\x0b\x32\x15.ignition.msgs.EntityB\"\n\x11\x63om.ignition.msgsB\rContactProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_entity__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_joint__wrench__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTACT = _descriptor.Descriptor(
  name='Contact',
  full_name='ignition.msgs.Contact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Contact.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collision1', full_name='ignition.msgs.Contact.collision1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collision2', full_name='ignition.msgs.Contact.collision2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='ignition.msgs.Contact.position', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normal', full_name='ignition.msgs.Contact.normal', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth', full_name='ignition.msgs.Contact.depth', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrench', full_name='ignition.msgs.Contact.wrench', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='ignition.msgs.Contact.world', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=482,
)

_CONTACT.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_CONTACT.fields_by_name['collision1'].message_type = ignition_dot_msgs_dot_entity__pb2._ENTITY
_CONTACT.fields_by_name['collision2'].message_type = ignition_dot_msgs_dot_entity__pb2._ENTITY
_CONTACT.fields_by_name['position'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_CONTACT.fields_by_name['normal'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_CONTACT.fields_by_name['wrench'].message_type = ignition_dot_msgs_dot_joint__wrench__pb2._JOINTWRENCH
_CONTACT.fields_by_name['world'].message_type = ignition_dot_msgs_dot_entity__pb2._ENTITY
DESCRIPTOR.message_types_by_name['Contact'] = _CONTACT

Contact = _reflection.GeneratedProtocolMessageType('Contact', (_message.Message,), dict(
  DESCRIPTOR = _CONTACT,
  __module__ = 'ignition.msgs.contact_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Contact)
  ))
_sym_db.RegisterMessage(Contact)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\rContactProtos'))
# @@protoc_insertion_point(module_scope)
