# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/diagnostics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import time_pb2 as ignition_dot_msgs_dot_time__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/diagnostics.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1fignition/msgs/diagnostics.proto\x12\rignition.msgs\x1a\x18ignition/msgs/time.proto\x1a\x1aignition/msgs/header.proto\"\xb3\x02\n\x0b\x44iagnostics\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x31\n\x04time\x18\x02 \x03(\x0b\x32#.ignition.msgs.Diagnostics.DiagTime\x12&\n\treal_time\x18\x03 \x01(\x0b\x32\x13.ignition.msgs.Time\x12%\n\x08sim_time\x18\x04 \x01(\x0b\x32\x13.ignition.msgs.Time\x12\x18\n\x10real_time_factor\x18\x05 \x01(\x01\x1a\x61\n\x08\x44iagTime\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x07\x65lapsed\x18\x02 \x01(\x0b\x32\x13.ignition.msgs.Time\x12!\n\x04wall\x18\x03 \x01(\x0b\x32\x13.ignition.msgs.TimeB&\n\x11\x63om.ignition.msgsB\x11\x44iagnosticsProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_time__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIAGNOSTICS_DIAGTIME = _descriptor.Descriptor(
  name='DiagTime',
  full_name='ignition.msgs.Diagnostics.DiagTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Diagnostics.DiagTime.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elapsed', full_name='ignition.msgs.Diagnostics.DiagTime.elapsed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wall', full_name='ignition.msgs.Diagnostics.DiagTime.wall', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=412,
)

_DIAGNOSTICS = _descriptor.Descriptor(
  name='Diagnostics',
  full_name='ignition.msgs.Diagnostics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Diagnostics.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ignition.msgs.Diagnostics.time', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real_time', full_name='ignition.msgs.Diagnostics.real_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sim_time', full_name='ignition.msgs.Diagnostics.sim_time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real_time_factor', full_name='ignition.msgs.Diagnostics.real_time_factor', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DIAGNOSTICS_DIAGTIME, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=412,
)

_DIAGNOSTICS_DIAGTIME.fields_by_name['elapsed'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
_DIAGNOSTICS_DIAGTIME.fields_by_name['wall'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
_DIAGNOSTICS_DIAGTIME.containing_type = _DIAGNOSTICS
_DIAGNOSTICS.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_DIAGNOSTICS.fields_by_name['time'].message_type = _DIAGNOSTICS_DIAGTIME
_DIAGNOSTICS.fields_by_name['real_time'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
_DIAGNOSTICS.fields_by_name['sim_time'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
DESCRIPTOR.message_types_by_name['Diagnostics'] = _DIAGNOSTICS

Diagnostics = _reflection.GeneratedProtocolMessageType('Diagnostics', (_message.Message,), dict(

  DiagTime = _reflection.GeneratedProtocolMessageType('DiagTime', (_message.Message,), dict(
    DESCRIPTOR = _DIAGNOSTICS_DIAGTIME,
    __module__ = 'ignition.msgs.diagnostics_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.Diagnostics.DiagTime)
    ))
  ,
  DESCRIPTOR = _DIAGNOSTICS,
  __module__ = 'ignition.msgs.diagnostics_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Diagnostics)
  ))
_sym_db.RegisterMessage(Diagnostics)
_sym_db.RegisterMessage(Diagnostics.DiagTime)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\021DiagnosticsProtos'))
# @@protoc_insertion_point(module_scope)
