# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/distortion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import vector2d_pb2 as ignition_dot_msgs_dot_vector2d__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/distortion.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1eignition/msgs/distortion.proto\x12\rignition.msgs\x1a\x1cignition/msgs/vector2d.proto\x1a\x1aignition/msgs/header.proto\"\x98\x01\n\nDistortion\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\'\n\x06\x63\x65nter\x18\x02 \x01(\x0b\x32\x17.ignition.msgs.Vector2d\x12\n\n\x02k1\x18\x03 \x01(\x01\x12\n\n\x02k2\x18\x04 \x01(\x01\x12\n\n\x02k3\x18\x05 \x01(\x01\x12\n\n\x02p1\x18\x06 \x01(\x01\x12\n\n\x02p2\x18\x07 \x01(\x01\x42%\n\x11\x63om.ignition.msgsB\x10\x44istortionProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_vector2d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DISTORTION = _descriptor.Descriptor(
  name='Distortion',
  full_name='ignition.msgs.Distortion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Distortion.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='center', full_name='ignition.msgs.Distortion.center', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k1', full_name='ignition.msgs.Distortion.k1', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k2', full_name='ignition.msgs.Distortion.k2', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k3', full_name='ignition.msgs.Distortion.k3', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p1', full_name='ignition.msgs.Distortion.p1', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p2', full_name='ignition.msgs.Distortion.p2', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=260,
)

_DISTORTION.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_DISTORTION.fields_by_name['center'].message_type = ignition_dot_msgs_dot_vector2d__pb2._VECTOR2D
DESCRIPTOR.message_types_by_name['Distortion'] = _DISTORTION

Distortion = _reflection.GeneratedProtocolMessageType('Distortion', (_message.Message,), dict(
  DESCRIPTOR = _DISTORTION,
  __module__ = 'ignition.msgs.distortion_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Distortion)
  ))
_sym_db.RegisterMessage(Distortion)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\020DistortionProtos'))
# @@protoc_insertion_point(module_scope)
