# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/entity_factory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import light_pb2 as ignition_dot_msgs_dot_light__pb2
from ignition.msgs import model_pb2 as ignition_dot_msgs_dot_model__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/entity_factory.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\"ignition/msgs/entity_factory.proto\x12\rignition.msgs\x1a\x18ignition/msgs/pose.proto\x1a\x19ignition/msgs/light.proto\x1a\x19ignition/msgs/model.proto\x1a\x1aignition/msgs/header.proto\"\xa7\x02\n\rEntityFactory\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\r\n\x03sdf\x18\x02 \x01(\tH\x00\x12\x16\n\x0csdf_filename\x18\x03 \x01(\tH\x00\x12%\n\x05model\x18\x04 \x01(\x0b\x32\x14.ignition.msgs.ModelH\x00\x12%\n\x05light\x18\x05 \x01(\x0b\x32\x14.ignition.msgs.LightH\x00\x12\x14\n\nclone_name\x18\x06 \x01(\tH\x00\x12!\n\x04pose\x18\x07 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x16\n\x0e\x61llow_renaming\x18\t \x01(\x08\x12\x13\n\x0brelative_to\x18\n \x01(\tB\x06\n\x04\x66romB(\n\x11\x63om.ignition.msgsB\x13\x45ntityFactoryProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_light__pb2.DESCRIPTOR,ignition_dot_msgs_dot_model__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENTITYFACTORY = _descriptor.Descriptor(
  name='EntityFactory',
  full_name='ignition.msgs.EntityFactory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.EntityFactory.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdf', full_name='ignition.msgs.EntityFactory.sdf', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdf_filename', full_name='ignition.msgs.EntityFactory.sdf_filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='ignition.msgs.EntityFactory.model', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='light', full_name='ignition.msgs.EntityFactory.light', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clone_name', full_name='ignition.msgs.EntityFactory.clone_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.EntityFactory.pose', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.EntityFactory.name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allow_renaming', full_name='ignition.msgs.EntityFactory.allow_renaming', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relative_to', full_name='ignition.msgs.EntityFactory.relative_to', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='from', full_name='ignition.msgs.EntityFactory.from',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=162,
  serialized_end=457,
)

_ENTITYFACTORY.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_ENTITYFACTORY.fields_by_name['model'].message_type = ignition_dot_msgs_dot_model__pb2._MODEL
_ENTITYFACTORY.fields_by_name['light'].message_type = ignition_dot_msgs_dot_light__pb2._LIGHT
_ENTITYFACTORY.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_ENTITYFACTORY.oneofs_by_name['from'].fields.append(
  _ENTITYFACTORY.fields_by_name['sdf'])
_ENTITYFACTORY.fields_by_name['sdf'].containing_oneof = _ENTITYFACTORY.oneofs_by_name['from']
_ENTITYFACTORY.oneofs_by_name['from'].fields.append(
  _ENTITYFACTORY.fields_by_name['sdf_filename'])
_ENTITYFACTORY.fields_by_name['sdf_filename'].containing_oneof = _ENTITYFACTORY.oneofs_by_name['from']
_ENTITYFACTORY.oneofs_by_name['from'].fields.append(
  _ENTITYFACTORY.fields_by_name['model'])
_ENTITYFACTORY.fields_by_name['model'].containing_oneof = _ENTITYFACTORY.oneofs_by_name['from']
_ENTITYFACTORY.oneofs_by_name['from'].fields.append(
  _ENTITYFACTORY.fields_by_name['light'])
_ENTITYFACTORY.fields_by_name['light'].containing_oneof = _ENTITYFACTORY.oneofs_by_name['from']
_ENTITYFACTORY.oneofs_by_name['from'].fields.append(
  _ENTITYFACTORY.fields_by_name['clone_name'])
_ENTITYFACTORY.fields_by_name['clone_name'].containing_oneof = _ENTITYFACTORY.oneofs_by_name['from']
DESCRIPTOR.message_types_by_name['EntityFactory'] = _ENTITYFACTORY

EntityFactory = _reflection.GeneratedProtocolMessageType('EntityFactory', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYFACTORY,
  __module__ = 'ignition.msgs.entity_factory_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.EntityFactory)
  ))
_sym_db.RegisterMessage(EntityFactory)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\023EntityFactoryProtos'))
# @@protoc_insertion_point(module_scope)
