# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/fluid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/fluid.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x19ignition/msgs/fluid.proto\x12\rignition.msgs\x1a\x1cignition/msgs/vector3d.proto\x1a\x1aignition/msgs/header.proto\"g\n\x05\x46luid\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12)\n\x08position\x18\x03 \x03(\x0b\x32\x17.ignition.msgs.Vector3dB \n\x11\x63om.ignition.msgsB\x0b\x46luidProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLUID = _descriptor.Descriptor(
  name='Fluid',
  full_name='ignition.msgs.Fluid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Fluid.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Fluid.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='ignition.msgs.Fluid.position', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=205,
)

_FLUID.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_FLUID.fields_by_name['position'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Fluid'] = _FLUID

Fluid = _reflection.GeneratedProtocolMessageType('Fluid', (_message.Message,), dict(
  DESCRIPTOR = _FLUID,
  __module__ = 'ignition.msgs.fluid_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Fluid)
  ))
_sym_db.RegisterMessage(Fluid)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\013FluidProtos'))
# @@protoc_insertion_point(module_scope)
