# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/fog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import color_pb2 as ignition_dot_msgs_dot_color__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/fog.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x17ignition/msgs/fog.proto\x12\rignition.msgs\x1a\x19ignition/msgs/color.proto\x1a\x1aignition/msgs/header.proto\"\xec\x01\n\x03\x46og\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.ignition.msgs.Fog.FogType\x12#\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x14.ignition.msgs.Color\x12\x0f\n\x07\x64\x65nsity\x18\x04 \x01(\x02\x12\r\n\x05start\x18\x05 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x06 \x01(\x02\"B\n\x07\x46ogType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06LINEAR\x10\x01\x12\x0f\n\x0b\x45XPONENTIAL\x10\x02\x12\x10\n\x0c\x45XPONENTIAL2\x10\x03\x42\x1e\n\x11\x63om.ignition.msgsB\tFogProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_color__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FOG_FOGTYPE = _descriptor.EnumDescriptor(
  name='FogType',
  full_name='ignition.msgs.Fog.FogType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINEAR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPONENTIAL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPONENTIAL2', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=268,
  serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_FOG_FOGTYPE)


_FOG = _descriptor.Descriptor(
  name='Fog',
  full_name='ignition.msgs.Fog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Fog.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Fog.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='ignition.msgs.Fog.color', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='density', full_name='ignition.msgs.Fog.density', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='ignition.msgs.Fog.start', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='ignition.msgs.Fog.end', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FOG_FOGTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=334,
)

_FOG.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_FOG.fields_by_name['type'].enum_type = _FOG_FOGTYPE
_FOG.fields_by_name['color'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_FOG_FOGTYPE.containing_type = _FOG
DESCRIPTOR.message_types_by_name['Fog'] = _FOG

Fog = _reflection.GeneratedProtocolMessageType('Fog', (_message.Message,), dict(
  DESCRIPTOR = _FOG,
  __module__ = 'ignition.msgs.fog_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Fog)
  ))
_sym_db.RegisterMessage(Fog)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\tFogProtos'))
# @@protoc_insertion_point(module_scope)
