# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/gps_sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import sensor_noise_pb2 as ignition_dot_msgs_dot_sensor__noise__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/gps_sensor.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1eignition/msgs/gps_sensor.proto\x12\rignition.msgs\x1a ignition/msgs/sensor_noise.proto\x1a\x1aignition/msgs/header.proto\"\x8f\x02\n\tGPSSensor\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x32\n\x08position\x18\x02 \x01(\x0b\x32 .ignition.msgs.GPSSensor.Sensing\x12\x32\n\x08velocity\x18\x03 \x01(\x0b\x32 .ignition.msgs.GPSSensor.Sensing\x1as\n\x07Sensing\x12\x34\n\x10horizontal_noise\x18\x01 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoise\x12\x32\n\x0evertical_noise\x18\x02 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoiseB\x1b\n\x11\x63om.ignition.msgsB\x06Protosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_sensor__noise__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GPSSENSOR_SENSING = _descriptor.Descriptor(
  name='Sensing',
  full_name='ignition.msgs.GPSSensor.Sensing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='horizontal_noise', full_name='ignition.msgs.GPSSensor.Sensing.horizontal_noise', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertical_noise', full_name='ignition.msgs.GPSSensor.Sensing.vertical_noise', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=383,
)

_GPSSENSOR = _descriptor.Descriptor(
  name='GPSSensor',
  full_name='ignition.msgs.GPSSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.GPSSensor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='ignition.msgs.GPSSensor.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='ignition.msgs.GPSSensor.velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GPSSENSOR_SENSING, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=383,
)

_GPSSENSOR_SENSING.fields_by_name['horizontal_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_GPSSENSOR_SENSING.fields_by_name['vertical_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_GPSSENSOR_SENSING.containing_type = _GPSSENSOR
_GPSSENSOR.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_GPSSENSOR.fields_by_name['position'].message_type = _GPSSENSOR_SENSING
_GPSSENSOR.fields_by_name['velocity'].message_type = _GPSSENSOR_SENSING
DESCRIPTOR.message_types_by_name['GPSSensor'] = _GPSSENSOR

GPSSensor = _reflection.GeneratedProtocolMessageType('GPSSensor', (_message.Message,), dict(

  Sensing = _reflection.GeneratedProtocolMessageType('Sensing', (_message.Message,), dict(
    DESCRIPTOR = _GPSSENSOR_SENSING,
    __module__ = 'ignition.msgs.gps_sensor_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.GPSSensor.Sensing)
    ))
  ,
  DESCRIPTOR = _GPSSENSOR,
  __module__ = 'ignition.msgs.gps_sensor_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.GPSSensor)
  ))
_sym_db.RegisterMessage(GPSSensor)
_sym_db.RegisterMessage(GPSSensor.Sensing)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\006Protos'))
# @@protoc_insertion_point(module_scope)
