# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/gui_camera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import track_visual_pb2 as ignition_dot_msgs_dot_track__visual__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/gui_camera.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1eignition/msgs/gui_camera.proto\x12\rignition.msgs\x1a\x18ignition/msgs/pose.proto\x1a ignition/msgs/track_visual.proto\x1a\x1aignition/msgs/header.proto\"\xc0\x01\n\tGUICamera\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0fview_controller\x18\x03 \x01(\t\x12!\n\x04pose\x18\x04 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12)\n\x05track\x18\x05 \x01(\x0b\x32\x1a.ignition.msgs.TrackVisual\x12\x17\n\x0fprojection_type\x18\x06 \x01(\tB$\n\x11\x63om.ignition.msgsB\x0fGUICameraProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_track__visual__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GUICAMERA = _descriptor.Descriptor(
  name='GUICamera',
  full_name='ignition.msgs.GUICamera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.GUICamera.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.GUICamera.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_controller', full_name='ignition.msgs.GUICamera.view_controller', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.GUICamera.pose', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track', full_name='ignition.msgs.GUICamera.track', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projection_type', full_name='ignition.msgs.GUICamera.projection_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=330,
)

_GUICAMERA.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_GUICAMERA.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_GUICAMERA.fields_by_name['track'].message_type = ignition_dot_msgs_dot_track__visual__pb2._TRACKVISUAL
DESCRIPTOR.message_types_by_name['GUICamera'] = _GUICAMERA

GUICamera = _reflection.GeneratedProtocolMessageType('GUICamera', (_message.Message,), dict(
  DESCRIPTOR = _GUICAMERA,
  __module__ = 'ignition.msgs.gui_camera_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.GUICamera)
  ))
_sym_db.RegisterMessage(GUICamera)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\017GUICameraProtos'))
# @@protoc_insertion_point(module_scope)
