# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/gui.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import gui_camera_pb2 as ignition_dot_msgs_dot_gui__camera__pb2
from ignition.msgs import plugin_pb2 as ignition_dot_msgs_dot_plugin__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/gui.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x17ignition/msgs/gui.proto\x12\rignition.msgs\x1a\x1eignition/msgs/gui_camera.proto\x1a\x1aignition/msgs/plugin.proto\x1a\x1aignition/msgs/header.proto\"\x91\x01\n\x03GUI\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x12\n\nfullscreen\x18\x02 \x01(\x08\x12(\n\x06\x63\x61mera\x18\x03 \x01(\x0b\x32\x18.ignition.msgs.GUICamera\x12%\n\x06plugin\x18\x04 \x03(\x0b\x32\x15.ignition.msgs.PluginB\x1e\n\x11\x63om.ignition.msgsB\tGUIProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_gui__camera__pb2.DESCRIPTOR,ignition_dot_msgs_dot_plugin__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GUI = _descriptor.Descriptor(
  name='GUI',
  full_name='ignition.msgs.GUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.GUI.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fullscreen', full_name='ignition.msgs.GUI.fullscreen', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='camera', full_name='ignition.msgs.GUI.camera', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='plugin', full_name='ignition.msgs.GUI.plugin', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=276,
)

_GUI.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_GUI.fields_by_name['camera'].message_type = ignition_dot_msgs_dot_gui__camera__pb2._GUICAMERA
_GUI.fields_by_name['plugin'].message_type = ignition_dot_msgs_dot_plugin__pb2._PLUGIN
DESCRIPTOR.message_types_by_name['GUI'] = _GUI

GUI = _reflection.GeneratedProtocolMessageType('GUI', (_message.Message,), dict(
  DESCRIPTOR = _GUI,
  __module__ = 'ignition.msgs.gui_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.GUI)
  ))
_sym_db.RegisterMessage(GUI)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\tGUIProtos'))
# @@protoc_insertion_point(module_scope)
