# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/imu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import quaternion_pb2 as ignition_dot_msgs_dot_quaternion__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/imu.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x17ignition/msgs/imu.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\x1a\x1cignition/msgs/vector3d.proto\x1a\x1eignition/msgs/quaternion.proto\"\xda\x01\n\x03IMU\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x13\n\x0b\x65ntity_name\x18\x02 \x01(\t\x12.\n\x0borientation\x18\x03 \x01(\x0b\x32\x19.ignition.msgs.Quaternion\x12\x31\n\x10\x61ngular_velocity\x18\x04 \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12\x34\n\x13linear_acceleration\x18\x05 \x01(\x0b\x32\x17.ignition.msgs.Vector3dB\x1e\n\x11\x63om.ignition.msgsB\tIMUProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_quaternion__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMU = _descriptor.Descriptor(
  name='IMU',
  full_name='ignition.msgs.IMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.IMU.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='ignition.msgs.IMU.entity_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='ignition.msgs.IMU.orientation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='ignition.msgs.IMU.angular_velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='ignition.msgs.IMU.linear_acceleration', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=351,
)

_IMU.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_IMU.fields_by_name['orientation'].message_type = ignition_dot_msgs_dot_quaternion__pb2._QUATERNION
_IMU.fields_by_name['angular_velocity'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_IMU.fields_by_name['linear_acceleration'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['IMU'] = _IMU

IMU = _reflection.GeneratedProtocolMessageType('IMU', (_message.Message,), dict(
  DESCRIPTOR = _IMU,
  __module__ = 'ignition.msgs.imu_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.IMU)
  ))
_sym_db.RegisterMessage(IMU)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\tIMUProtos'))
# @@protoc_insertion_point(module_scope)
