# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/imu_sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import sensor_noise_pb2 as ignition_dot_msgs_dot_sensor__noise__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/imu_sensor.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1eignition/msgs/imu_sensor.proto\x12\rignition.msgs\x1a ignition/msgs/sensor_noise.proto\x1a\x1aignition/msgs/header.proto\x1a\x1cignition/msgs/vector3d.proto\"\xa2\x06\n\tIMUSensor\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x42\n\x10\x61ngular_velocity\x18\x02 \x01(\x0b\x32(.ignition.msgs.IMUSensor.AngularVelocity\x12H\n\x13linear_acceleration\x18\x03 \x01(\x0b\x32+.ignition.msgs.IMUSensor.LinearAcceleration\x12Q\n\x15orientation_ref_frame\x18\x04 \x01(\x0b\x32\x32.ignition.msgs.IMUSensor.OrientationReferenceFrame\x1a\x98\x01\n\x0f\x41ngularVelocity\x12+\n\x07x_noise\x18\x01 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoise\x12+\n\x07y_noise\x18\x02 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoise\x12+\n\x07z_noise\x18\x03 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoise\x1a\x9b\x01\n\x12LinearAcceleration\x12+\n\x07x_noise\x18\x01 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoise\x12+\n\x07y_noise\x18\x02 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoise\x12+\n\x07z_noise\x18\x03 \x01(\x0b\x32\x1a.ignition.msgs.SensorNoise\x1a\xd3\x01\n\x19OrientationReferenceFrame\x12\x14\n\x0clocalization\x18\x01 \x01(\t\x12+\n\ncustom_rpy\x18\x02 \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12\x1f\n\x17\x63ustom_rpy_parent_frame\x18\x03 \x01(\t\x12.\n\rgravity_dir_x\x18\x04 \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12\"\n\x1agravity_dir_x_parent_frame\x18\x05 \x01(\tB$\n\x11\x63om.ignition.msgsB\x0fIMUSensorProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_sensor__noise__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMUSENSOR_ANGULARVELOCITY = _descriptor.Descriptor(
  name='AngularVelocity',
  full_name='ignition.msgs.IMUSensor.AngularVelocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_noise', full_name='ignition.msgs.IMUSensor.AngularVelocity.x_noise', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_noise', full_name='ignition.msgs.IMUSensor.AngularVelocity.y_noise', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_noise', full_name='ignition.msgs.IMUSensor.AngularVelocity.z_noise', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=572,
)

_IMUSENSOR_LINEARACCELERATION = _descriptor.Descriptor(
  name='LinearAcceleration',
  full_name='ignition.msgs.IMUSensor.LinearAcceleration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_noise', full_name='ignition.msgs.IMUSensor.LinearAcceleration.x_noise', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_noise', full_name='ignition.msgs.IMUSensor.LinearAcceleration.y_noise', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_noise', full_name='ignition.msgs.IMUSensor.LinearAcceleration.z_noise', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=730,
)

_IMUSENSOR_ORIENTATIONREFERENCEFRAME = _descriptor.Descriptor(
  name='OrientationReferenceFrame',
  full_name='ignition.msgs.IMUSensor.OrientationReferenceFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localization', full_name='ignition.msgs.IMUSensor.OrientationReferenceFrame.localization', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_rpy', full_name='ignition.msgs.IMUSensor.OrientationReferenceFrame.custom_rpy', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_rpy_parent_frame', full_name='ignition.msgs.IMUSensor.OrientationReferenceFrame.custom_rpy_parent_frame', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gravity_dir_x', full_name='ignition.msgs.IMUSensor.OrientationReferenceFrame.gravity_dir_x', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gravity_dir_x_parent_frame', full_name='ignition.msgs.IMUSensor.OrientationReferenceFrame.gravity_dir_x_parent_frame', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=944,
)

_IMUSENSOR = _descriptor.Descriptor(
  name='IMUSensor',
  full_name='ignition.msgs.IMUSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.IMUSensor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='ignition.msgs.IMUSensor.angular_velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='ignition.msgs.IMUSensor.linear_acceleration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation_ref_frame', full_name='ignition.msgs.IMUSensor.orientation_ref_frame', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMUSENSOR_ANGULARVELOCITY, _IMUSENSOR_LINEARACCELERATION, _IMUSENSOR_ORIENTATIONREFERENCEFRAME, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=944,
)

_IMUSENSOR_ANGULARVELOCITY.fields_by_name['x_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_IMUSENSOR_ANGULARVELOCITY.fields_by_name['y_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_IMUSENSOR_ANGULARVELOCITY.fields_by_name['z_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_IMUSENSOR_ANGULARVELOCITY.containing_type = _IMUSENSOR
_IMUSENSOR_LINEARACCELERATION.fields_by_name['x_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_IMUSENSOR_LINEARACCELERATION.fields_by_name['y_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_IMUSENSOR_LINEARACCELERATION.fields_by_name['z_noise'].message_type = ignition_dot_msgs_dot_sensor__noise__pb2._SENSORNOISE
_IMUSENSOR_LINEARACCELERATION.containing_type = _IMUSENSOR
_IMUSENSOR_ORIENTATIONREFERENCEFRAME.fields_by_name['custom_rpy'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_IMUSENSOR_ORIENTATIONREFERENCEFRAME.fields_by_name['gravity_dir_x'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_IMUSENSOR_ORIENTATIONREFERENCEFRAME.containing_type = _IMUSENSOR
_IMUSENSOR.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_IMUSENSOR.fields_by_name['angular_velocity'].message_type = _IMUSENSOR_ANGULARVELOCITY
_IMUSENSOR.fields_by_name['linear_acceleration'].message_type = _IMUSENSOR_LINEARACCELERATION
_IMUSENSOR.fields_by_name['orientation_ref_frame'].message_type = _IMUSENSOR_ORIENTATIONREFERENCEFRAME
DESCRIPTOR.message_types_by_name['IMUSensor'] = _IMUSENSOR

IMUSensor = _reflection.GeneratedProtocolMessageType('IMUSensor', (_message.Message,), dict(

  AngularVelocity = _reflection.GeneratedProtocolMessageType('AngularVelocity', (_message.Message,), dict(
    DESCRIPTOR = _IMUSENSOR_ANGULARVELOCITY,
    __module__ = 'ignition.msgs.imu_sensor_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.IMUSensor.AngularVelocity)
    ))
  ,

  LinearAcceleration = _reflection.GeneratedProtocolMessageType('LinearAcceleration', (_message.Message,), dict(
    DESCRIPTOR = _IMUSENSOR_LINEARACCELERATION,
    __module__ = 'ignition.msgs.imu_sensor_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.IMUSensor.LinearAcceleration)
    ))
  ,

  OrientationReferenceFrame = _reflection.GeneratedProtocolMessageType('OrientationReferenceFrame', (_message.Message,), dict(
    DESCRIPTOR = _IMUSENSOR_ORIENTATIONREFERENCEFRAME,
    __module__ = 'ignition.msgs.imu_sensor_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.IMUSensor.OrientationReferenceFrame)
    ))
  ,
  DESCRIPTOR = _IMUSENSOR,
  __module__ = 'ignition.msgs.imu_sensor_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.IMUSensor)
  ))
_sym_db.RegisterMessage(IMUSensor)
_sym_db.RegisterMessage(IMUSensor.AngularVelocity)
_sym_db.RegisterMessage(IMUSensor.LinearAcceleration)
_sym_db.RegisterMessage(IMUSensor.OrientationReferenceFrame)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\017IMUSensorProtos'))
# @@protoc_insertion_point(module_scope)
