# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/light.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import color_pb2 as ignition_dot_msgs_dot_color__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/light.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x19ignition/msgs/light.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\x1a\x18ignition/msgs/pose.proto\x1a\x1cignition/msgs/vector3d.proto\x1a\x19ignition/msgs/color.proto\"\xa2\x04\n\x05Light\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x04type\x18\x03 \x01(\x0e\x32\x1e.ignition.msgs.Light.LightType\x12!\n\x04pose\x18\x04 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12%\n\x07\x64iffuse\x18\x05 \x01(\x0b\x32\x14.ignition.msgs.Color\x12&\n\x08specular\x18\x06 \x01(\x0b\x32\x14.ignition.msgs.Color\x12\x1c\n\x14\x61ttenuation_constant\x18\x07 \x01(\x02\x12\x1a\n\x12\x61ttenuation_linear\x18\x08 \x01(\x02\x12\x1d\n\x15\x61ttenuation_quadratic\x18\t \x01(\x02\x12*\n\tdirection\x18\n \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12\r\n\x05range\x18\x0b \x01(\x02\x12\x14\n\x0c\x63\x61st_shadows\x18\x0c \x01(\x08\x12\x18\n\x10spot_inner_angle\x18\r \x01(\x02\x12\x18\n\x10spot_outer_angle\x18\x0e \x01(\x02\x12\x14\n\x0cspot_falloff\x18\x0f \x01(\x02\x12\n\n\x02id\x18\x10 \x01(\r\x12\x11\n\tparent_id\x18\x11 \x01(\r\"1\n\tLightType\x12\t\n\x05POINT\x10\x00\x12\x08\n\x04SPOT\x10\x01\x12\x0f\n\x0b\x44IRECTIONAL\x10\x02\x42 \n\x11\x63om.ignition.msgsB\x0bLightProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_color__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LIGHT_LIGHTTYPE = _descriptor.EnumDescriptor(
  name='LightType',
  full_name='ignition.msgs.Light.LightType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POINT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPOT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRECTIONAL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=653,
  serialized_end=702,
)
_sym_db.RegisterEnumDescriptor(_LIGHT_LIGHTTYPE)


_LIGHT = _descriptor.Descriptor(
  name='Light',
  full_name='ignition.msgs.Light',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Light.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Light.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Light.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Light.pose', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diffuse', full_name='ignition.msgs.Light.diffuse', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='specular', full_name='ignition.msgs.Light.specular', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attenuation_constant', full_name='ignition.msgs.Light.attenuation_constant', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attenuation_linear', full_name='ignition.msgs.Light.attenuation_linear', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attenuation_quadratic', full_name='ignition.msgs.Light.attenuation_quadratic', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='ignition.msgs.Light.direction', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='ignition.msgs.Light.range', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cast_shadows', full_name='ignition.msgs.Light.cast_shadows', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spot_inner_angle', full_name='ignition.msgs.Light.spot_inner_angle', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spot_outer_angle', full_name='ignition.msgs.Light.spot_outer_angle', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spot_falloff', full_name='ignition.msgs.Light.spot_falloff', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.Light.id', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='ignition.msgs.Light.parent_id', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LIGHT_LIGHTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=702,
)

_LIGHT.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_LIGHT.fields_by_name['type'].enum_type = _LIGHT_LIGHTTYPE
_LIGHT.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_LIGHT.fields_by_name['diffuse'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_LIGHT.fields_by_name['specular'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_LIGHT.fields_by_name['direction'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_LIGHT_LIGHTTYPE.containing_type = _LIGHT
DESCRIPTOR.message_types_by_name['Light'] = _LIGHT

Light = _reflection.GeneratedProtocolMessageType('Light', (_message.Message,), dict(
  DESCRIPTOR = _LIGHT,
  __module__ = 'ignition.msgs.light_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Light)
  ))
_sym_db.RegisterMessage(Light)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\013LightProtos'))
# @@protoc_insertion_point(module_scope)
