# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/link.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import inertial_pb2 as ignition_dot_msgs_dot_inertial__pb2
from ignition.msgs import collision_pb2 as ignition_dot_msgs_dot_collision__pb2
from ignition.msgs import visual_pb2 as ignition_dot_msgs_dot_visual__pb2
from ignition.msgs import light_pb2 as ignition_dot_msgs_dot_light__pb2
from ignition.msgs import sensor_pb2 as ignition_dot_msgs_dot_sensor__pb2
from ignition.msgs import projector_pb2 as ignition_dot_msgs_dot_projector__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import battery_pb2 as ignition_dot_msgs_dot_battery__pb2
from ignition.msgs import density_pb2 as ignition_dot_msgs_dot_density__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/link.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x18ignition/msgs/link.proto\x12\rignition.msgs\x1a\x1cignition/msgs/inertial.proto\x1a\x1dignition/msgs/collision.proto\x1a\x1aignition/msgs/visual.proto\x1a\x19ignition/msgs/light.proto\x1a\x1aignition/msgs/sensor.proto\x1a\x1dignition/msgs/projector.proto\x1a\x18ignition/msgs/pose.proto\x1a\x1bignition/msgs/battery.proto\x1a\x1bignition/msgs/density.proto\x1a\x1aignition/msgs/header.proto\"\x92\x04\n\x04Link\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cself_collide\x18\x04 \x01(\x08\x12\x0f\n\x07gravity\x18\x05 \x01(\x08\x12\x11\n\tkinematic\x18\x06 \x01(\x08\x12\x0f\n\x07\x65nabled\x18\x07 \x01(\x08\x12\'\n\x07\x64\x65nsity\x18\x08 \x01(\x0b\x32\x16.ignition.msgs.Density\x12)\n\x08inertial\x18\t \x01(\x0b\x32\x17.ignition.msgs.Inertial\x12!\n\x04pose\x18\n \x01(\x0b\x32\x13.ignition.msgs.Pose\x12%\n\x06visual\x18\x0b \x03(\x0b\x32\x15.ignition.msgs.Visual\x12+\n\tcollision\x18\x0c \x03(\x0b\x32\x18.ignition.msgs.Collision\x12%\n\x06sensor\x18\r \x03(\x0b\x32\x15.ignition.msgs.Sensor\x12+\n\tprojector\x18\x0e \x03(\x0b\x32\x18.ignition.msgs.Projector\x12\x11\n\tcanonical\x18\x0f \x01(\x08\x12\'\n\x07\x62\x61ttery\x18\x10 \x03(\x0b\x32\x16.ignition.msgs.Battery\x12#\n\x05light\x18\x11 \x03(\x0b\x32\x14.ignition.msgs.LightB\x1f\n\x11\x63om.ignition.msgsB\nLinkProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_inertial__pb2.DESCRIPTOR,ignition_dot_msgs_dot_collision__pb2.DESCRIPTOR,ignition_dot_msgs_dot_visual__pb2.DESCRIPTOR,ignition_dot_msgs_dot_light__pb2.DESCRIPTOR,ignition_dot_msgs_dot_sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_projector__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_battery__pb2.DESCRIPTOR,ignition_dot_msgs_dot_density__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LINK = _descriptor.Descriptor(
  name='Link',
  full_name='ignition.msgs.Link',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Link.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.Link.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Link.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='self_collide', full_name='ignition.msgs.Link.self_collide', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gravity', full_name='ignition.msgs.Link.gravity', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kinematic', full_name='ignition.msgs.Link.kinematic', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='ignition.msgs.Link.enabled', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='density', full_name='ignition.msgs.Link.density', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inertial', full_name='ignition.msgs.Link.inertial', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Link.pose', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visual', full_name='ignition.msgs.Link.visual', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collision', full_name='ignition.msgs.Link.collision', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor', full_name='ignition.msgs.Link.sensor', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projector', full_name='ignition.msgs.Link.projector', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canonical', full_name='ignition.msgs.Link.canonical', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery', full_name='ignition.msgs.Link.battery', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='light', full_name='ignition.msgs.Link.light', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=861,
)

_LINK.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_LINK.fields_by_name['density'].message_type = ignition_dot_msgs_dot_density__pb2._DENSITY
_LINK.fields_by_name['inertial'].message_type = ignition_dot_msgs_dot_inertial__pb2._INERTIAL
_LINK.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_LINK.fields_by_name['visual'].message_type = ignition_dot_msgs_dot_visual__pb2._VISUAL
_LINK.fields_by_name['collision'].message_type = ignition_dot_msgs_dot_collision__pb2._COLLISION
_LINK.fields_by_name['sensor'].message_type = ignition_dot_msgs_dot_sensor__pb2._SENSOR
_LINK.fields_by_name['projector'].message_type = ignition_dot_msgs_dot_projector__pb2._PROJECTOR
_LINK.fields_by_name['battery'].message_type = ignition_dot_msgs_dot_battery__pb2._BATTERY
_LINK.fields_by_name['light'].message_type = ignition_dot_msgs_dot_light__pb2._LIGHT
DESCRIPTOR.message_types_by_name['Link'] = _LINK

Link = _reflection.GeneratedProtocolMessageType('Link', (_message.Message,), dict(
  DESCRIPTOR = _LINK,
  __module__ = 'ignition.msgs.link_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Link)
  ))
_sym_db.RegisterMessage(Link)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\nLinkProtos'))
# @@protoc_insertion_point(module_scope)
