# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/log_playback_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import time_pb2 as ignition_dot_msgs_dot_time__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/log_playback_control.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n(ignition/msgs/log_playback_control.proto\x12\rignition.msgs\x1a\x18ignition/msgs/time.proto\x1a\x1aignition/msgs/header.proto\"\xa2\x01\n\x12LogPlaybackControl\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\r\n\x05pause\x18\x02 \x01(\x08\x12\x12\n\nmulti_step\x18\x03 \x01(\x11\x12\x0e\n\x06rewind\x18\x04 \x01(\x08\x12\x0f\n\x07\x66orward\x18\x05 \x01(\x08\x12!\n\x04seek\x18\x06 \x01(\x0b\x32\x13.ignition.msgs.TimeB-\n\x11\x63om.ignition.msgsB\x18LogPlaybackControlProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_time__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGPLAYBACKCONTROL = _descriptor.Descriptor(
  name='LogPlaybackControl',
  full_name='ignition.msgs.LogPlaybackControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.LogPlaybackControl.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pause', full_name='ignition.msgs.LogPlaybackControl.pause', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_step', full_name='ignition.msgs.LogPlaybackControl.multi_step', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rewind', full_name='ignition.msgs.LogPlaybackControl.rewind', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forward', full_name='ignition.msgs.LogPlaybackControl.forward', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seek', full_name='ignition.msgs.LogPlaybackControl.seek', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=276,
)

_LOGPLAYBACKCONTROL.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_LOGPLAYBACKCONTROL.fields_by_name['seek'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
DESCRIPTOR.message_types_by_name['LogPlaybackControl'] = _LOGPLAYBACKCONTROL

LogPlaybackControl = _reflection.GeneratedProtocolMessageType('LogPlaybackControl', (_message.Message,), dict(
  DESCRIPTOR = _LOGPLAYBACKCONTROL,
  __module__ = 'ignition.msgs.log_playback_control_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.LogPlaybackControl)
  ))
_sym_db.RegisterMessage(LogPlaybackControl)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\030LogPlaybackControlProtos'))
# @@protoc_insertion_point(module_scope)
