# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/magnetometer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/magnetometer.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n ignition/msgs/magnetometer.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\x1a\x1cignition/msgs/vector3d.proto\"c\n\x0cMagnetometer\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12,\n\x0b\x66ield_tesla\x18\x02 \x01(\x0b\x32\x17.ignition.msgs.Vector3dB\'\n\x11\x63om.ignition.msgsB\x12MagnetometerProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAGNETOMETER = _descriptor.Descriptor(
  name='Magnetometer',
  full_name='ignition.msgs.Magnetometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Magnetometer.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field_tesla', full_name='ignition.msgs.Magnetometer.field_tesla', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=208,
)

_MAGNETOMETER.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_MAGNETOMETER.fields_by_name['field_tesla'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Magnetometer'] = _MAGNETOMETER

Magnetometer = _reflection.GeneratedProtocolMessageType('Magnetometer', (_message.Message,), dict(
  DESCRIPTOR = _MAGNETOMETER,
  __module__ = 'ignition.msgs.magnetometer_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Magnetometer)
  ))
_sym_db.RegisterMessage(Magnetometer)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\022MagnetometerProtos'))
# @@protoc_insertion_point(module_scope)
