# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/marker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import time_pb2 as ignition_dot_msgs_dot_time__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import material_pb2 as ignition_dot_msgs_dot_material__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/marker.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1aignition/msgs/marker.proto\x12\rignition.msgs\x1a\x18ignition/msgs/time.proto\x1a\x18ignition/msgs/pose.proto\x1a\x1cignition/msgs/vector3d.proto\x1a\x1cignition/msgs/material.proto\x1a\x1aignition/msgs/header.proto\"\xc8\x05\n\x06Marker\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12,\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1c.ignition.msgs.Marker.Action\x12\n\n\x02ns\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x04\x12\r\n\x05layer\x18\x05 \x01(\x05\x12(\n\x04type\x18\x06 \x01(\x0e\x32\x1a.ignition.msgs.Marker.Type\x12%\n\x08lifetime\x18\x07 \x01(\x0b\x32\x13.ignition.msgs.Time\x12!\n\x04pose\x18\x08 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12&\n\x05scale\x18\t \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12)\n\x08material\x18\n \x01(\x0b\x32\x17.ignition.msgs.Material\x12&\n\x05point\x18\x0b \x03(\x0b\x32\x17.ignition.msgs.Vector3d\x12\x0c\n\x04text\x18\x0c \x01(\t\x12\x0e\n\x06parent\x18\r \x01(\t\x12\x34\n\nvisibility\x18\x0e \x01(\x0e\x32 .ignition.msgs.Marker.Visibility\"\xa1\x01\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x42OX\x10\x01\x12\x0c\n\x08\x43YLINDER\x10\x02\x12\r\n\tLINE_LIST\x10\x04\x12\x0e\n\nLINE_STRIP\x10\x03\x12\n\n\x06POINTS\x10\x05\x12\n\n\x06SPHERE\x10\x06\x12\x08\n\x04TEXT\x10\x07\x12\x10\n\x0cTRIANGLE_FAN\x10\x08\x12\x11\n\rTRIANGLE_LIST\x10\t\x12\x12\n\x0eTRIANGLE_STRIP\x10\n\"\x1e\n\nVisibility\x12\x07\n\x03GUI\x10\x00\x12\x07\n\x03\x41LL\x10\x01\";\n\x06\x41\x63tion\x12\x0e\n\nADD_MODIFY\x10\x00\x12\x11\n\rDELETE_MARKER\x10\x01\x12\x0e\n\nDELETE_ALL\x10\x02\x42!\n\x11\x63om.ignition.msgsB\x0cMarkerProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_time__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_material__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MARKER_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='ignition.msgs.Marker.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOX', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CYLINDER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINE_LIST', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINE_STRIP', index=4, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POINTS', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPHERE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIANGLE_FAN', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIANGLE_LIST', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIANGLE_STRIP', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=644,
  serialized_end=805,
)
_sym_db.RegisterEnumDescriptor(_MARKER_TYPE)

_MARKER_VISIBILITY = _descriptor.EnumDescriptor(
  name='Visibility',
  full_name='ignition.msgs.Marker.Visibility',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GUI', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=807,
  serialized_end=837,
)
_sym_db.RegisterEnumDescriptor(_MARKER_VISIBILITY)

_MARKER_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='ignition.msgs.Marker.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD_MODIFY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_MARKER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ALL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=839,
  serialized_end=898,
)
_sym_db.RegisterEnumDescriptor(_MARKER_ACTION)


_MARKER = _descriptor.Descriptor(
  name='Marker',
  full_name='ignition.msgs.Marker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Marker.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='ignition.msgs.Marker.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ns', full_name='ignition.msgs.Marker.ns', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.Marker.id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer', full_name='ignition.msgs.Marker.layer', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Marker.type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lifetime', full_name='ignition.msgs.Marker.lifetime', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Marker.pose', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='ignition.msgs.Marker.scale', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='ignition.msgs.Marker.material', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='ignition.msgs.Marker.point', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='ignition.msgs.Marker.text', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='ignition.msgs.Marker.parent', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='ignition.msgs.Marker.visibility', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MARKER_TYPE,
    _MARKER_VISIBILITY,
    _MARKER_ACTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=898,
)

_MARKER.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_MARKER.fields_by_name['action'].enum_type = _MARKER_ACTION
_MARKER.fields_by_name['type'].enum_type = _MARKER_TYPE
_MARKER.fields_by_name['lifetime'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
_MARKER.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_MARKER.fields_by_name['scale'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_MARKER.fields_by_name['material'].message_type = ignition_dot_msgs_dot_material__pb2._MATERIAL
_MARKER.fields_by_name['point'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_MARKER.fields_by_name['visibility'].enum_type = _MARKER_VISIBILITY
_MARKER_TYPE.containing_type = _MARKER
_MARKER_VISIBILITY.containing_type = _MARKER
_MARKER_ACTION.containing_type = _MARKER
DESCRIPTOR.message_types_by_name['Marker'] = _MARKER

Marker = _reflection.GeneratedProtocolMessageType('Marker', (_message.Message,), dict(
  DESCRIPTOR = _MARKER,
  __module__ = 'ignition.msgs.marker_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Marker)
  ))
_sym_db.RegisterMessage(Marker)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\014MarkerProtos'))
# @@protoc_insertion_point(module_scope)
