# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/material.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import color_pb2 as ignition_dot_msgs_dot_color__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/material.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1cignition/msgs/material.proto\x12\rignition.msgs\x1a\x19ignition/msgs/color.proto\x1a\x1aignition/msgs/header.proto\"\x8c\x07\n\x08Material\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12.\n\x06script\x18\x02 \x01(\x0b\x32\x1e.ignition.msgs.Material.Script\x12\x37\n\x0bshader_type\x18\x03 \x01(\x0e\x32\".ignition.msgs.Material.ShaderType\x12\x12\n\nnormal_map\x18\x04 \x01(\t\x12%\n\x07\x61mbient\x18\x05 \x01(\x0b\x32\x14.ignition.msgs.Color\x12%\n\x07\x64iffuse\x18\x06 \x01(\x0b\x32\x14.ignition.msgs.Color\x12&\n\x08specular\x18\x07 \x01(\x0b\x32\x14.ignition.msgs.Color\x12&\n\x08\x65missive\x18\x08 \x01(\x0b\x32\x14.ignition.msgs.Color\x12\x10\n\x08lighting\x18\t \x01(\x08\x12(\n\x03pbr\x18\n \x01(\x0b\x32\x1b.ignition.msgs.Material.PBR\x1a#\n\x06Script\x12\x0b\n\x03uri\x18\x01 \x03(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a\xfc\x02\n\x03PBR\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.ignition.msgs.Material.PBR.WorkflowType\x12\x12\n\nalbedo_map\x18\x02 \x01(\t\x12\x12\n\nnormal_map\x18\x03 \x01(\t\x12\x11\n\tmetalness\x18\x04 \x01(\x01\x12\x15\n\rmetalness_map\x18\x05 \x01(\t\x12\x11\n\troughness\x18\x06 \x01(\x01\x12\x15\n\rroughness_map\x18\x07 \x01(\t\x12\x12\n\nglossiness\x18\x08 \x01(\x01\x12\x16\n\x0eglossiness_map\x18\t \x01(\t\x12\x14\n\x0cspecular_map\x18\n \x01(\t\x12\x17\n\x0f\x65nvironment_map\x18\x0b \x01(\t\x12\x1d\n\x15\x61mbient_occlusion_map\x18\x0c \x01(\t\x12\x14\n\x0c\x65missive_map\x18\r \x01(\t\"1\n\x0cWorkflowType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05METAL\x10\x01\x12\x0c\n\x08SPECULAR\x10\x02\"^\n\nShaderType\x12\n\n\x06VERTEX\x10\x00\x12\t\n\x05PIXEL\x10\x01\x12\x1b\n\x17NORMAL_MAP_OBJECT_SPACE\x10\x02\x12\x1c\n\x18NORMAL_MAP_TANGENT_SPACE\x10\x03\x42#\n\x11\x63om.ignition.msgsB\x0eMaterialProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_color__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MATERIAL_PBR_WORKFLOWTYPE = _descriptor.EnumDescriptor(
  name='WorkflowType',
  full_name='ignition.msgs.Material.PBR.WorkflowType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECULAR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=866,
  serialized_end=915,
)
_sym_db.RegisterEnumDescriptor(_MATERIAL_PBR_WORKFLOWTYPE)

_MATERIAL_SHADERTYPE = _descriptor.EnumDescriptor(
  name='ShaderType',
  full_name='ignition.msgs.Material.ShaderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VERTEX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PIXEL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL_MAP_OBJECT_SPACE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL_MAP_TANGENT_SPACE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=917,
  serialized_end=1011,
)
_sym_db.RegisterEnumDescriptor(_MATERIAL_SHADERTYPE)


_MATERIAL_SCRIPT = _descriptor.Descriptor(
  name='Script',
  full_name='ignition.msgs.Material.Script',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='ignition.msgs.Material.Script.uri', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Material.Script.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=532,
)

_MATERIAL_PBR = _descriptor.Descriptor(
  name='PBR',
  full_name='ignition.msgs.Material.PBR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Material.PBR.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='albedo_map', full_name='ignition.msgs.Material.PBR.albedo_map', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normal_map', full_name='ignition.msgs.Material.PBR.normal_map', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metalness', full_name='ignition.msgs.Material.PBR.metalness', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metalness_map', full_name='ignition.msgs.Material.PBR.metalness_map', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roughness', full_name='ignition.msgs.Material.PBR.roughness', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roughness_map', full_name='ignition.msgs.Material.PBR.roughness_map', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glossiness', full_name='ignition.msgs.Material.PBR.glossiness', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glossiness_map', full_name='ignition.msgs.Material.PBR.glossiness_map', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='specular_map', full_name='ignition.msgs.Material.PBR.specular_map', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='environment_map', full_name='ignition.msgs.Material.PBR.environment_map', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ambient_occlusion_map', full_name='ignition.msgs.Material.PBR.ambient_occlusion_map', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emissive_map', full_name='ignition.msgs.Material.PBR.emissive_map', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MATERIAL_PBR_WORKFLOWTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=915,
)

_MATERIAL = _descriptor.Descriptor(
  name='Material',
  full_name='ignition.msgs.Material',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Material.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='script', full_name='ignition.msgs.Material.script', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shader_type', full_name='ignition.msgs.Material.shader_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normal_map', full_name='ignition.msgs.Material.normal_map', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ambient', full_name='ignition.msgs.Material.ambient', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diffuse', full_name='ignition.msgs.Material.diffuse', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='specular', full_name='ignition.msgs.Material.specular', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emissive', full_name='ignition.msgs.Material.emissive', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lighting', full_name='ignition.msgs.Material.lighting', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pbr', full_name='ignition.msgs.Material.pbr', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MATERIAL_SCRIPT, _MATERIAL_PBR, ],
  enum_types=[
    _MATERIAL_SHADERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=1011,
)

_MATERIAL_SCRIPT.containing_type = _MATERIAL
_MATERIAL_PBR.fields_by_name['type'].enum_type = _MATERIAL_PBR_WORKFLOWTYPE
_MATERIAL_PBR.containing_type = _MATERIAL
_MATERIAL_PBR_WORKFLOWTYPE.containing_type = _MATERIAL_PBR
_MATERIAL.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_MATERIAL.fields_by_name['script'].message_type = _MATERIAL_SCRIPT
_MATERIAL.fields_by_name['shader_type'].enum_type = _MATERIAL_SHADERTYPE
_MATERIAL.fields_by_name['ambient'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_MATERIAL.fields_by_name['diffuse'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_MATERIAL.fields_by_name['specular'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_MATERIAL.fields_by_name['emissive'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_MATERIAL.fields_by_name['pbr'].message_type = _MATERIAL_PBR
_MATERIAL_SHADERTYPE.containing_type = _MATERIAL
DESCRIPTOR.message_types_by_name['Material'] = _MATERIAL

Material = _reflection.GeneratedProtocolMessageType('Material', (_message.Message,), dict(

  Script = _reflection.GeneratedProtocolMessageType('Script', (_message.Message,), dict(
    DESCRIPTOR = _MATERIAL_SCRIPT,
    __module__ = 'ignition.msgs.material_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.Material.Script)
    ))
  ,

  PBR = _reflection.GeneratedProtocolMessageType('PBR', (_message.Message,), dict(
    DESCRIPTOR = _MATERIAL_PBR,
    __module__ = 'ignition.msgs.material_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.Material.PBR)
    ))
  ,
  DESCRIPTOR = _MATERIAL,
  __module__ = 'ignition.msgs.material_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Material)
  ))
_sym_db.RegisterMessage(Material)
_sym_db.RegisterMessage(Material.Script)
_sym_db.RegisterMessage(Material.PBR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\016MaterialProtos'))
# @@protoc_insertion_point(module_scope)
