# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import axis_aligned_box_pb2 as ignition_dot_msgs_dot_axis__aligned__box__pb2
from ignition.msgs import joint_pb2 as ignition_dot_msgs_dot_joint__pb2
from ignition.msgs import link_pb2 as ignition_dot_msgs_dot_link__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import visual_pb2 as ignition_dot_msgs_dot_visual__pb2
from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/model.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x19ignition/msgs/model.proto\x12\rignition.msgs\x1a$ignition/msgs/axis_aligned_box.proto\x1a\x19ignition/msgs/joint.proto\x1a\x18ignition/msgs/link.proto\x1a\x18ignition/msgs/pose.proto\x1a\x1aignition/msgs/visual.proto\x1a\x1cignition/msgs/vector3d.proto\x1a\x1aignition/msgs/header.proto\"\x96\x03\n\x05Model\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x11\n\tis_static\x18\x04 \x01(\x08\x12!\n\x04pose\x18\x05 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12#\n\x05joint\x18\x06 \x03(\x0b\x32\x14.ignition.msgs.Joint\x12!\n\x04link\x18\x07 \x03(\x0b\x32\x13.ignition.msgs.Link\x12\x0f\n\x07\x64\x65leted\x18\x08 \x01(\x08\x12%\n\x06visual\x18\t \x03(\x0b\x32\x15.ignition.msgs.Visual\x12&\n\x05scale\x18\n \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12\x14\n\x0cself_collide\x18\x0b \x01(\x08\x12#\n\x05model\x18\x0c \x03(\x0b\x32\x14.ignition.msgs.Model\x12\x33\n\x0c\x62ounding_box\x18\r \x01(\x0b\x32\x1d.ignition.msgs.AxisAlignedBoxB \n\x11\x63om.ignition.msgsB\x0bModelProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_axis__aligned__box__pb2.DESCRIPTOR,ignition_dot_msgs_dot_joint__pb2.DESCRIPTOR,ignition_dot_msgs_dot_link__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_visual__pb2.DESCRIPTOR,ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='ignition.msgs.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Model.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Model.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.Model.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_static', full_name='ignition.msgs.Model.is_static', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Model.pose', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joint', full_name='ignition.msgs.Model.joint', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='link', full_name='ignition.msgs.Model.link', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='ignition.msgs.Model.deleted', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visual', full_name='ignition.msgs.Model.visual', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='ignition.msgs.Model.scale', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='self_collide', full_name='ignition.msgs.Model.self_collide', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='ignition.msgs.Model.model', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bounding_box', full_name='ignition.msgs.Model.bounding_box', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=654,
)

_MODEL.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_MODEL.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_MODEL.fields_by_name['joint'].message_type = ignition_dot_msgs_dot_joint__pb2._JOINT
_MODEL.fields_by_name['link'].message_type = ignition_dot_msgs_dot_link__pb2._LINK
_MODEL.fields_by_name['visual'].message_type = ignition_dot_msgs_dot_visual__pb2._VISUAL
_MODEL.fields_by_name['scale'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
_MODEL.fields_by_name['model'].message_type = _MODEL
_MODEL.fields_by_name['bounding_box'].message_type = ignition_dot_msgs_dot_axis__aligned__box__pb2._AXISALIGNEDBOX
DESCRIPTOR.message_types_by_name['Model'] = _MODEL

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'ignition.msgs.model_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Model)
  ))
_sym_db.RegisterMessage(Model)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\013ModelProtos'))
# @@protoc_insertion_point(module_scope)
