# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/odometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import twist_pb2 as ignition_dot_msgs_dot_twist__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/odometry.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1cignition/msgs/odometry.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\x1a\x18ignition/msgs/pose.proto\x1a\x19ignition/msgs/twist.proto\"y\n\x08Odometry\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12!\n\x04pose\x18\x02 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12#\n\x05twist\x18\x03 \x01(\x0b\x32\x14.ignition.msgs.TwistB#\n\x11\x63om.ignition.msgsB\x0eOdometryProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_twist__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ODOMETRY = _descriptor.Descriptor(
  name='Odometry',
  full_name='ignition.msgs.Odometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Odometry.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Odometry.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='twist', full_name='ignition.msgs.Odometry.twist', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=249,
)

_ODOMETRY.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_ODOMETRY.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_ODOMETRY.fields_by_name['twist'].message_type = ignition_dot_msgs_dot_twist__pb2._TWIST
DESCRIPTOR.message_types_by_name['Odometry'] = _ODOMETRY

Odometry = _reflection.GeneratedProtocolMessageType('Odometry', (_message.Message,), dict(
  DESCRIPTOR = _ODOMETRY,
  __module__ = 'ignition.msgs.odometry_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Odometry)
  ))
_sym_db.RegisterMessage(Odometry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\016OdometryProtos'))
# @@protoc_insertion_point(module_scope)
