# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import double_v_pb2 as ignition_dot_msgs_dot_double__v__pb2
from ignition.msgs import clock_pb2 as ignition_dot_msgs_dot_clock__pb2
from ignition.msgs import cmd_vel2d_pb2 as ignition_dot_msgs_dot_cmd__vel2d__pb2
from ignition.msgs import image_pb2 as ignition_dot_msgs_dot_image__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import pose_v_pb2 as ignition_dot_msgs_dot_pose__v__pb2
from ignition.msgs import stringmsg_v_pb2 as ignition_dot_msgs_dot_stringmsg__v__pb2
from ignition.msgs import time_pb2 as ignition_dot_msgs_dot_time__pb2
from ignition.msgs import web_request_pb2 as ignition_dot_msgs_dot_web__request__pb2
from ignition.msgs import world_stats_pb2 as ignition_dot_msgs_dot_world__stats__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/packet.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1aignition/msgs/packet.proto\x12\rignition.msgs\x1a\x1cignition/msgs/double_v.proto\x1a\x19ignition/msgs/clock.proto\x1a\x1dignition/msgs/cmd_vel2d.proto\x1a\x19ignition/msgs/image.proto\x1a\x18ignition/msgs/pose.proto\x1a\x1aignition/msgs/pose_v.proto\x1a\x1fignition/msgs/stringmsg_v.proto\x1a\x18ignition/msgs/time.proto\x1a\x1fignition/msgs/web_request.proto\x1a\x1fignition/msgs/world_stats.proto\"\xe8\x03\n\x06Packet\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12,\n\tcmd_vel2d\x18\x03 \x01(\x0b\x32\x17.ignition.msgs.CmdVel2DH\x00\x12%\n\x05image\x18\x04 \x01(\x0b\x32\x14.ignition.msgs.ImageH\x00\x12\x32\n\x0cstring_msg_v\x18\x05 \x01(\x0b\x32\x1a.ignition.msgs.StringMsg_VH\x00\x12\x30\n\x0bweb_request\x18\x06 \x01(\x0b\x32\x19.ignition.msgs.WebRequestH\x00\x12#\n\x04pose\x18\x07 \x01(\x0b\x32\x13.ignition.msgs.PoseH\x00\x12*\n\x07\x64oublev\x18\x08 \x01(\x0b\x32\x17.ignition.msgs.Double_VH\x00\x12\'\n\x06pose_v\x18\t \x01(\x0b\x32\x15.ignition.msgs.Pose_VH\x00\x12#\n\x04time\x18\n \x01(\x0b\x32\x13.ignition.msgs.TimeH\x00\x12%\n\x05\x63lock\x18\x0b \x01(\x0b\x32\x14.ignition.msgs.ClockH\x00\x12\x35\n\x0bworld_stats\x18\x0c \x01(\x0b\x32\x1e.ignition.msgs.WorldStatisticsH\x00\x42\t\n\x07\x63ontentB!\n\x11\x63om.ignition.msgsB\x0cPacketProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_double__v__pb2.DESCRIPTOR,ignition_dot_msgs_dot_clock__pb2.DESCRIPTOR,ignition_dot_msgs_dot_cmd__vel2d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_image__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__v__pb2.DESCRIPTOR,ignition_dot_msgs_dot_stringmsg__v__pb2.DESCRIPTOR,ignition_dot_msgs_dot_time__pb2.DESCRIPTOR,ignition_dot_msgs_dot_web__request__pb2.DESCRIPTOR,ignition_dot_msgs_dot_world__stats__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='ignition.msgs.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='ignition.msgs.Packet.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Packet.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd_vel2d', full_name='ignition.msgs.Packet.cmd_vel2d', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='ignition.msgs.Packet.image', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_msg_v', full_name='ignition.msgs.Packet.string_msg_v', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='web_request', full_name='ignition.msgs.Packet.web_request', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Packet.pose', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doublev', full_name='ignition.msgs.Packet.doublev', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose_v', full_name='ignition.msgs.Packet.pose_v', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ignition.msgs.Packet.time', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clock', full_name='ignition.msgs.Packet.clock', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world_stats', full_name='ignition.msgs.Packet.world_stats', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='ignition.msgs.Packet.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=340,
  serialized_end=828,
)

_PACKET.fields_by_name['cmd_vel2d'].message_type = ignition_dot_msgs_dot_cmd__vel2d__pb2._CMDVEL2D
_PACKET.fields_by_name['image'].message_type = ignition_dot_msgs_dot_image__pb2._IMAGE
_PACKET.fields_by_name['string_msg_v'].message_type = ignition_dot_msgs_dot_stringmsg__v__pb2._STRINGMSG_V
_PACKET.fields_by_name['web_request'].message_type = ignition_dot_msgs_dot_web__request__pb2._WEBREQUEST
_PACKET.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_PACKET.fields_by_name['doublev'].message_type = ignition_dot_msgs_dot_double__v__pb2._DOUBLE_V
_PACKET.fields_by_name['pose_v'].message_type = ignition_dot_msgs_dot_pose__v__pb2._POSE_V
_PACKET.fields_by_name['time'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
_PACKET.fields_by_name['clock'].message_type = ignition_dot_msgs_dot_clock__pb2._CLOCK
_PACKET.fields_by_name['world_stats'].message_type = ignition_dot_msgs_dot_world__stats__pb2._WORLDSTATISTICS
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['cmd_vel2d'])
_PACKET.fields_by_name['cmd_vel2d'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['image'])
_PACKET.fields_by_name['image'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['string_msg_v'])
_PACKET.fields_by_name['string_msg_v'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['web_request'])
_PACKET.fields_by_name['web_request'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['pose'])
_PACKET.fields_by_name['pose'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['doublev'])
_PACKET.fields_by_name['doublev'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['pose_v'])
_PACKET.fields_by_name['pose_v'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['time'])
_PACKET.fields_by_name['time'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['clock'])
_PACKET.fields_by_name['clock'].containing_oneof = _PACKET.oneofs_by_name['content']
_PACKET.oneofs_by_name['content'].fields.append(
  _PACKET.fields_by_name['world_stats'])
_PACKET.fields_by_name['world_stats'].containing_oneof = _PACKET.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'ignition.msgs.packet_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Packet)
  ))
_sym_db.RegisterMessage(Packet)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\014PacketProtos'))
# @@protoc_insertion_point(module_scope)
