# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import any_pb2 as ignition_dot_msgs_dot_any__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/param.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x19ignition/msgs/param.proto\x12\rignition.msgs\x1a\x17ignition/msgs/any.proto\x1a\x1aignition/msgs/header.proto\"\xcb\x01\n\x05Param\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x30\n\x06params\x18\x02 \x03(\x0b\x32 .ignition.msgs.Param.ParamsEntry\x12&\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x14.ignition.msgs.Param\x1a\x41\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.ignition.msgs.Any:\x02\x38\x01\x42 \n\x11\x63om.ignition.msgsB\x0b\x45mptyProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_any__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARAM_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='ignition.msgs.Param.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ignition.msgs.Param.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ignition.msgs.Param.ParamsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=301,
)

_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='ignition.msgs.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Param.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='ignition.msgs.Param.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children', full_name='ignition.msgs.Param.children', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PARAM_PARAMSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=301,
)

_PARAM_PARAMSENTRY.fields_by_name['value'].message_type = ignition_dot_msgs_dot_any__pb2._ANY
_PARAM_PARAMSENTRY.containing_type = _PARAM
_PARAM.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_PARAM.fields_by_name['params'].message_type = _PARAM_PARAMSENTRY
_PARAM.fields_by_name['children'].message_type = _PARAM
DESCRIPTOR.message_types_by_name['Param'] = _PARAM

Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), dict(

  ParamsEntry = _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PARAM_PARAMSENTRY,
    __module__ = 'ignition.msgs.param_pb2'
    # @@protoc_insertion_point(class_scope:ignition.msgs.Param.ParamsEntry)
    ))
  ,
  DESCRIPTOR = _PARAM,
  __module__ = 'ignition.msgs.param_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Param)
  ))
_sym_db.RegisterMessage(Param)
_sym_db.RegisterMessage(Param.ParamsEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\013EmptyProtos'))
_PARAM_PARAMSENTRY.has_options = True
_PARAM_PARAMSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
