# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/pid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import double_pb2 as ignition_dot_msgs_dot_double__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/pid.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x17ignition/msgs/pid.proto\x12\rignition.msgs\x1a\x1aignition/msgs/double.proto\x1a\x1aignition/msgs/header.proto\"\x82\x04\n\x03PID\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x12\n\x06target\x18\x02 \x01(\x01\x42\x02\x18\x01\x12\x12\n\x06p_gain\x18\x03 \x01(\x01\x42\x02\x18\x01\x12\x12\n\x06i_gain\x18\x04 \x01(\x01\x42\x02\x18\x01\x12\x12\n\x06\x64_gain\x18\x05 \x01(\x01\x42\x02\x18\x01\x12\x11\n\x05i_max\x18\x06 \x01(\x01\x42\x02\x18\x01\x12\x11\n\x05i_min\x18\x07 \x01(\x01\x42\x02\x18\x01\x12\x11\n\x05limit\x18\x08 \x01(\x01\x42\x02\x18\x01\x12.\n\x0ftarget_optional\x18\t \x01(\x0b\x32\x15.ignition.msgs.Double\x12.\n\x0fp_gain_optional\x18\n \x01(\x0b\x32\x15.ignition.msgs.Double\x12.\n\x0fi_gain_optional\x18\x0b \x01(\x0b\x32\x15.ignition.msgs.Double\x12.\n\x0f\x64_gain_optional\x18\x0c \x01(\x0b\x32\x15.ignition.msgs.Double\x12-\n\x0ei_max_optional\x18\r \x01(\x0b\x32\x15.ignition.msgs.Double\x12-\n\x0ei_min_optional\x18\x0e \x01(\x0b\x32\x15.ignition.msgs.Double\x12-\n\x0elimit_optional\x18\x0f \x01(\x0b\x32\x15.ignition.msgs.DoubleB\x1e\n\x11\x63om.ignition.msgsB\tPIDProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_double__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PID = _descriptor.Descriptor(
  name='PID',
  full_name='ignition.msgs.PID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.PID.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='ignition.msgs.PID.target', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='p_gain', full_name='ignition.msgs.PID.p_gain', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='i_gain', full_name='ignition.msgs.PID.i_gain', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='d_gain', full_name='ignition.msgs.PID.d_gain', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='i_max', full_name='ignition.msgs.PID.i_max', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='i_min', full_name='ignition.msgs.PID.i_min', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='limit', full_name='ignition.msgs.PID.limit', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='target_optional', full_name='ignition.msgs.PID.target_optional', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p_gain_optional', full_name='ignition.msgs.PID.p_gain_optional', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i_gain_optional', full_name='ignition.msgs.PID.i_gain_optional', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d_gain_optional', full_name='ignition.msgs.PID.d_gain_optional', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i_max_optional', full_name='ignition.msgs.PID.i_max_optional', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i_min_optional', full_name='ignition.msgs.PID.i_min_optional', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_optional', full_name='ignition.msgs.PID.limit_optional', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=613,
)

_PID.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_PID.fields_by_name['target_optional'].message_type = ignition_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['p_gain_optional'].message_type = ignition_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['i_gain_optional'].message_type = ignition_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['d_gain_optional'].message_type = ignition_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['i_max_optional'].message_type = ignition_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['i_min_optional'].message_type = ignition_dot_msgs_dot_double__pb2._DOUBLE
_PID.fields_by_name['limit_optional'].message_type = ignition_dot_msgs_dot_double__pb2._DOUBLE
DESCRIPTOR.message_types_by_name['PID'] = _PID

PID = _reflection.GeneratedProtocolMessageType('PID', (_message.Message,), dict(
  DESCRIPTOR = _PID,
  __module__ = 'ignition.msgs.pid_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.PID)
  ))
_sym_db.RegisterMessage(PID)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\tPIDProtos'))
_PID.fields_by_name['target'].has_options = True
_PID.fields_by_name['target']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_PID.fields_by_name['p_gain'].has_options = True
_PID.fields_by_name['p_gain']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_PID.fields_by_name['i_gain'].has_options = True
_PID.fields_by_name['i_gain']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_PID.fields_by_name['d_gain'].has_options = True
_PID.fields_by_name['d_gain']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_PID.fields_by_name['i_max'].has_options = True
_PID.fields_by_name['i_max']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_PID.fields_by_name['i_min'].has_options = True
_PID.fields_by_name['i_min']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_PID.fields_by_name['limit'].has_options = True
_PID.fields_by_name['limit']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
# @@protoc_insertion_point(module_scope)
