# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/pointcloud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/pointcloud.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1eignition/msgs/pointcloud.proto\x12\rignition.msgs\x1a\x1cignition/msgs/vector3d.proto\x1a\x1aignition/msgs/header.proto\"\\\n\nPointCloud\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\'\n\x06points\x18\x02 \x03(\x0b\x32\x17.ignition.msgs.Vector3dB%\n\x11\x63om.ignition.msgsB\x10PointCloudProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POINTCLOUD = _descriptor.Descriptor(
  name='PointCloud',
  full_name='ignition.msgs.PointCloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.PointCloud.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='ignition.msgs.PointCloud.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=199,
)

_POINTCLOUD.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_POINTCLOUD.fields_by_name['points'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['PointCloud'] = _POINTCLOUD

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUD,
  __module__ = 'ignition.msgs.pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.PointCloud)
  ))
_sym_db.RegisterMessage(PointCloud)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\020PointCloudProtos'))
# @@protoc_insertion_point(module_scope)
