# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/polylinegeom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import vector2d_pb2 as ignition_dot_msgs_dot_vector2d__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/polylinegeom.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n ignition/msgs/polylinegeom.proto\x12\rignition.msgs\x1a\x1cignition/msgs/vector2d.proto\x1a\x1aignition/msgs/header.proto\"i\n\x08Polyline\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0e\n\x06height\x18\x02 \x01(\x01\x12&\n\x05point\x18\x03 \x03(\x0b\x32\x17.ignition.msgs.Vector2dB\x1b\n\x11\x63om.ignition.msgsB\x06Protosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_vector2d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POLYLINE = _descriptor.Descriptor(
  name='Polyline',
  full_name='ignition.msgs.Polyline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Polyline.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='ignition.msgs.Polyline.height', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='ignition.msgs.Polyline.point', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=214,
)

_POLYLINE.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_POLYLINE.fields_by_name['point'].message_type = ignition_dot_msgs_dot_vector2d__pb2._VECTOR2D
DESCRIPTOR.message_types_by_name['Polyline'] = _POLYLINE

Polyline = _reflection.GeneratedProtocolMessageType('Polyline', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE,
  __module__ = 'ignition.msgs.polylinegeom_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Polyline)
  ))
_sym_db.RegisterMessage(Polyline)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\006Protos'))
# @@protoc_insertion_point(module_scope)
