# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/pose_animation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import time_pb2 as ignition_dot_msgs_dot_time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/pose_animation.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\"ignition/msgs/pose_animation.proto\x12\rignition.msgs\x1a\x18ignition/msgs/pose.proto\x1a\x18ignition/msgs/time.proto\"{\n\rPoseAnimation\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\r\x12!\n\x04pose\x18\x03 \x03(\x0b\x32\x13.ignition.msgs.Pose\x12!\n\x04time\x18\x04 \x03(\x0b\x32\x13.ignition.msgs.TimeB(\n\x11\x63om.ignition.msgsB\x13PoseAnimationProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_time__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSEANIMATION = _descriptor.Descriptor(
  name='PoseAnimation',
  full_name='ignition.msgs.PoseAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='ignition.msgs.PoseAnimation.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='ignition.msgs.PoseAnimation.model_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.PoseAnimation.pose', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ignition.msgs.PoseAnimation.time', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=228,
)

_POSEANIMATION.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_POSEANIMATION.fields_by_name['time'].message_type = ignition_dot_msgs_dot_time__pb2._TIME
DESCRIPTOR.message_types_by_name['PoseAnimation'] = _POSEANIMATION

PoseAnimation = _reflection.GeneratedProtocolMessageType('PoseAnimation', (_message.Message,), dict(
  DESCRIPTOR = _POSEANIMATION,
  __module__ = 'ignition.msgs.pose_animation_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.PoseAnimation)
  ))
_sym_db.RegisterMessage(PoseAnimation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\023PoseAnimationProtos'))
# @@protoc_insertion_point(module_scope)
