# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/projector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/projector.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1dignition/msgs/projector.proto\x12\rignition.msgs\x1a\x18ignition/msgs/pose.proto\x1a\x1aignition/msgs/header.proto\"\xb7\x01\n\tProjector\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07texture\x18\x03 \x01(\t\x12!\n\x04pose\x18\x04 \x01(\x0b\x32\x13.ignition.msgs.Pose\x12\x0b\n\x03\x66ov\x18\x05 \x01(\x01\x12\x11\n\tnear_clip\x18\x06 \x01(\x01\x12\x10\n\x08\x66\x61r_clip\x18\x07 \x01(\x01\x12\x0f\n\x07\x65nabled\x18\x08 \x01(\x08\x42$\n\x11\x63om.ignition.msgsB\x0fProjectorProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROJECTOR = _descriptor.Descriptor(
  name='Projector',
  full_name='ignition.msgs.Projector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Projector.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Projector.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='texture', full_name='ignition.msgs.Projector.texture', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Projector.pose', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fov', full_name='ignition.msgs.Projector.fov', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='near_clip', full_name='ignition.msgs.Projector.near_clip', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='far_clip', full_name='ignition.msgs.Projector.far_clip', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='ignition.msgs.Projector.enabled', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=286,
)

_PROJECTOR.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_PROJECTOR.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
DESCRIPTOR.message_types_by_name['Projector'] = _PROJECTOR

Projector = _reflection.GeneratedProtocolMessageType('Projector', (_message.Message,), dict(
  DESCRIPTOR = _PROJECTOR,
  __module__ = 'ignition.msgs.projector_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Projector)
  ))
_sym_db.RegisterMessage(Projector)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\017ProjectorProtos'))
# @@protoc_insertion_point(module_scope)
