# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import altimeter_sensor_pb2 as ignition_dot_msgs_dot_altimeter__sensor__pb2
from ignition.msgs import camerasensor_pb2 as ignition_dot_msgs_dot_camerasensor__pb2
from ignition.msgs import contactsensor_pb2 as ignition_dot_msgs_dot_contactsensor__pb2
from ignition.msgs import air_pressure_sensor_pb2 as ignition_dot_msgs_dot_air__pressure__sensor__pb2
from ignition.msgs import gps_sensor_pb2 as ignition_dot_msgs_dot_gps__sensor__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2
from ignition.msgs import imu_sensor_pb2 as ignition_dot_msgs_dot_imu__sensor__pb2
from ignition.msgs import lidar_sensor_pb2 as ignition_dot_msgs_dot_lidar__sensor__pb2
from ignition.msgs import logical_camera_sensor_pb2 as ignition_dot_msgs_dot_logical__camera__sensor__pb2
from ignition.msgs import magnetometer_sensor_pb2 as ignition_dot_msgs_dot_magnetometer__sensor__pb2
from ignition.msgs import pose_pb2 as ignition_dot_msgs_dot_pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/sensor.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1aignition/msgs/sensor.proto\x12\rignition.msgs\x1a$ignition/msgs/altimeter_sensor.proto\x1a ignition/msgs/camerasensor.proto\x1a!ignition/msgs/contactsensor.proto\x1a\'ignition/msgs/air_pressure_sensor.proto\x1a\x1eignition/msgs/gps_sensor.proto\x1a\x1aignition/msgs/header.proto\x1a\x1eignition/msgs/imu_sensor.proto\x1a ignition/msgs/lidar_sensor.proto\x1a)ignition/msgs/logical_camera_sensor.proto\x1a\'ignition/msgs/magnetometer_sensor.proto\x1a\x18ignition/msgs/pose.proto\"\x9c\x05\n\x06Sensor\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x0e\n\x06parent\x18\x04 \x01(\t\x12\x11\n\tparent_id\x18\x05 \x01(\r\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x11\n\talways_on\x18\x07 \x01(\x08\x12\x13\n\x0bupdate_rate\x18\x08 \x01(\x01\x12!\n\x04pose\x18\t \x01(\x0b\x32\x13.ignition.msgs.Pose\x12+\n\x06\x63\x61mera\x18\n \x01(\x0b\x32\x1b.ignition.msgs.CameraSensor\x12-\n\x07\x63ontact\x18\x0b \x01(\x0b\x32\x1c.ignition.msgs.ContactSensor\x12\x11\n\tvisualize\x18\x0c \x01(\x08\x12\r\n\x05topic\x18\r \x01(\t\x12:\n\x0elogical_camera\x18\x0e \x01(\x0b\x32\".ignition.msgs.LogicalCameraSensor\x12%\n\x03gps\x18\x0f \x01(\x0b\x32\x18.ignition.msgs.GPSSensor\x12%\n\x03imu\x18\x10 \x01(\x0b\x32\x18.ignition.msgs.IMUSensor\x12\x37\n\x0cmagnetometer\x18\x11 \x01(\x0b\x32!.ignition.msgs.MagnetometerSensor\x12\x31\n\taltimeter\x18\x12 \x01(\x0b\x32\x1e.ignition.msgs.AltimeterSensor\x12\x36\n\x0c\x61ir_pressure\x18\x13 \x01(\x0b\x32 .ignition.msgs.AirPressureSensor\x12)\n\x05lidar\x18\x14 \x01(\x0b\x32\x1a.ignition.msgs.LidarSensorB!\n\x11\x63om.ignition.msgsB\x0cSensorProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_altimeter__sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_camerasensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_contactsensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_air__pressure__sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_gps__sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,ignition_dot_msgs_dot_imu__sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_lidar__sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_logical__camera__sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_magnetometer__sensor__pb2.DESCRIPTOR,ignition_dot_msgs_dot_pose__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='ignition.msgs.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Sensor.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.Sensor.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.Sensor.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='ignition.msgs.Sensor.parent', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='ignition.msgs.Sensor.parent_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Sensor.type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='always_on', full_name='ignition.msgs.Sensor.always_on', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update_rate', full_name='ignition.msgs.Sensor.update_rate', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='ignition.msgs.Sensor.pose', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='camera', full_name='ignition.msgs.Sensor.camera', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contact', full_name='ignition.msgs.Sensor.contact', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visualize', full_name='ignition.msgs.Sensor.visualize', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topic', full_name='ignition.msgs.Sensor.topic', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logical_camera', full_name='ignition.msgs.Sensor.logical_camera', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps', full_name='ignition.msgs.Sensor.gps', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imu', full_name='ignition.msgs.Sensor.imu', index=15,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='magnetometer', full_name='ignition.msgs.Sensor.magnetometer', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altimeter', full_name='ignition.msgs.Sensor.altimeter', index=17,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='air_pressure', full_name='ignition.msgs.Sensor.air_pressure', index=18,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lidar', full_name='ignition.msgs.Sensor.lidar', index=19,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=1098,
)

_SENSOR.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_SENSOR.fields_by_name['pose'].message_type = ignition_dot_msgs_dot_pose__pb2._POSE
_SENSOR.fields_by_name['camera'].message_type = ignition_dot_msgs_dot_camerasensor__pb2._CAMERASENSOR
_SENSOR.fields_by_name['contact'].message_type = ignition_dot_msgs_dot_contactsensor__pb2._CONTACTSENSOR
_SENSOR.fields_by_name['logical_camera'].message_type = ignition_dot_msgs_dot_logical__camera__sensor__pb2._LOGICALCAMERASENSOR
_SENSOR.fields_by_name['gps'].message_type = ignition_dot_msgs_dot_gps__sensor__pb2._GPSSENSOR
_SENSOR.fields_by_name['imu'].message_type = ignition_dot_msgs_dot_imu__sensor__pb2._IMUSENSOR
_SENSOR.fields_by_name['magnetometer'].message_type = ignition_dot_msgs_dot_magnetometer__sensor__pb2._MAGNETOMETERSENSOR
_SENSOR.fields_by_name['altimeter'].message_type = ignition_dot_msgs_dot_altimeter__sensor__pb2._ALTIMETERSENSOR
_SENSOR.fields_by_name['air_pressure'].message_type = ignition_dot_msgs_dot_air__pressure__sensor__pb2._AIRPRESSURESENSOR
_SENSOR.fields_by_name['lidar'].message_type = ignition_dot_msgs_dot_lidar__sensor__pb2._LIDARSENSOR
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR,
  __module__ = 'ignition.msgs.sensor_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Sensor)
  ))
_sym_db.RegisterMessage(Sensor)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\014SensorProtos'))
# @@protoc_insertion_point(module_scope)
