# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/server_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/server_control.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\"ignition/msgs/server_control.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\"\xbf\x01\n\rServerControl\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x17\n\x0fsave_world_name\x18\x02 \x01(\t\x12\x15\n\rsave_filename\x18\x03 \x01(\t\x12\x15\n\ropen_filename\x18\x04 \x01(\t\x12\x11\n\tnew_world\x18\x05 \x01(\x08\x12\x0c\n\x04stop\x18\x06 \x01(\x08\x12\r\n\x05\x63lone\x18\x07 \x01(\x08\x12\x10\n\x08new_port\x18\x08 \x01(\rB(\n\x11\x63om.ignition.msgsB\x13ServerControlProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SERVERCONTROL = _descriptor.Descriptor(
  name='ServerControl',
  full_name='ignition.msgs.ServerControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.ServerControl.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_world_name', full_name='ignition.msgs.ServerControl.save_world_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_filename', full_name='ignition.msgs.ServerControl.save_filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open_filename', full_name='ignition.msgs.ServerControl.open_filename', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_world', full_name='ignition.msgs.ServerControl.new_world', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop', full_name='ignition.msgs.ServerControl.stop', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clone', full_name='ignition.msgs.ServerControl.clone', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_port', full_name='ignition.msgs.ServerControl.new_port', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=273,
)

_SERVERCONTROL.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['ServerControl'] = _SERVERCONTROL

ServerControl = _reflection.GeneratedProtocolMessageType('ServerControl', (_message.Message,), dict(
  DESCRIPTOR = _SERVERCONTROL,
  __module__ = 'ignition.msgs.server_control_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.ServerControl)
  ))
_sym_db.RegisterMessage(ServerControl)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\023ServerControlProtos'))
# @@protoc_insertion_point(module_scope)
