# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/shadows.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import color_pb2 as ignition_dot_msgs_dot_color__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/shadows.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1bignition/msgs/shadows.proto\x12\rignition.msgs\x1a\x19ignition/msgs/color.proto\x1a\x1aignition/msgs/header.proto\"\xf0\x01\n\x07Shadows\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.ignition.msgs.Shadows.ShadowType\x12#\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x14.ignition.msgs.Color\"h\n\nShadowType\x12\x14\n\x10STENCIL_ADDITIVE\x10\x00\x12\x16\n\x12STENCIL_MODULATIVE\x10\x01\x12\x14\n\x10TEXTURE_ADDITIVE\x10\x02\x12\x16\n\x12TEXTURE_MODULATIVE\x10\x03\x42\"\n\x11\x63om.ignition.msgsB\rShadowsProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_color__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SHADOWS_SHADOWTYPE = _descriptor.EnumDescriptor(
  name='ShadowType',
  full_name='ignition.msgs.Shadows.ShadowType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STENCIL_ADDITIVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STENCIL_MODULATIVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXTURE_ADDITIVE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXTURE_MODULATIVE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=238,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_SHADOWS_SHADOWTYPE)


_SHADOWS = _descriptor.Descriptor(
  name='Shadows',
  full_name='ignition.msgs.Shadows',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.Shadows.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.Shadows.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='ignition.msgs.Shadows.color', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SHADOWS_SHADOWTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=342,
)

_SHADOWS.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_SHADOWS.fields_by_name['type'].enum_type = _SHADOWS_SHADOWTYPE
_SHADOWS.fields_by_name['color'].message_type = ignition_dot_msgs_dot_color__pb2._COLOR
_SHADOWS_SHADOWTYPE.containing_type = _SHADOWS
DESCRIPTOR.message_types_by_name['Shadows'] = _SHADOWS

Shadows = _reflection.GeneratedProtocolMessageType('Shadows', (_message.Message,), dict(
  DESCRIPTOR = _SHADOWS,
  __module__ = 'ignition.msgs.shadows_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.Shadows)
  ))
_sym_db.RegisterMessage(Shadows)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\rShadowsProtos'))
# @@protoc_insertion_point(module_scope)
