# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/track_visual.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import vector3d_pb2 as ignition_dot_msgs_dot_vector3d__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/track_visual.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n ignition/msgs/track_visual.proto\x12\rignition.msgs\x1a\x1cignition/msgs/vector3d.proto\x1a\x1aignition/msgs/header.proto\"\xf3\x01\n\x0bTrackVisual\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x1b\n\x13inherit_orientation\x18\x04 \x01(\x08\x12\x10\n\x08min_dist\x18\x05 \x01(\x01\x12\x10\n\x08max_dist\x18\x06 \x01(\x01\x12\x0e\n\x06static\x18\x07 \x01(\x08\x12\x17\n\x0fuse_model_frame\x18\x08 \x01(\x08\x12$\n\x03xyz\x18\t \x01(\x0b\x32\x17.ignition.msgs.Vector3d\x12\x13\n\x0binherit_yaw\x18\n \x01(\x08\x42&\n\x11\x63om.ignition.msgsB\x11TrackVisualProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_vector3d__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRACKVISUAL = _descriptor.Descriptor(
  name='TrackVisual',
  full_name='ignition.msgs.TrackVisual',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.TrackVisual.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ignition.msgs.TrackVisual.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.TrackVisual.id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inherit_orientation', full_name='ignition.msgs.TrackVisual.inherit_orientation', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_dist', full_name='ignition.msgs.TrackVisual.min_dist', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_dist', full_name='ignition.msgs.TrackVisual.max_dist', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='static', full_name='ignition.msgs.TrackVisual.static', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_model_frame', full_name='ignition.msgs.TrackVisual.use_model_frame', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xyz', full_name='ignition.msgs.TrackVisual.xyz', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inherit_yaw', full_name='ignition.msgs.TrackVisual.inherit_yaw', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=353,
)

_TRACKVISUAL.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_TRACKVISUAL.fields_by_name['xyz'].message_type = ignition_dot_msgs_dot_vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['TrackVisual'] = _TRACKVISUAL

TrackVisual = _reflection.GeneratedProtocolMessageType('TrackVisual', (_message.Message,), dict(
  DESCRIPTOR = _TRACKVISUAL,
  __module__ = 'ignition.msgs.track_visual_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.TrackVisual)
  ))
_sym_db.RegisterMessage(TrackVisual)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\021TrackVisualProtos'))
# @@protoc_insertion_point(module_scope)
