# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/uint32.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/uint32.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1aignition/msgs/uint32.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\"=\n\x06UInt32\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\rB!\n\x11\x63om.ignition.msgsB\x0cUInt32Protosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UINT32 = _descriptor.Descriptor(
  name='UInt32',
  full_name='ignition.msgs.UInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.UInt32.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ignition.msgs.UInt32.data', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=134,
)

_UINT32.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['UInt32'] = _UINT32

UInt32 = _reflection.GeneratedProtocolMessageType('UInt32', (_message.Message,), dict(
  DESCRIPTOR = _UINT32,
  __module__ = 'ignition.msgs.uint32_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.UInt32)
  ))
_sym_db.RegisterMessage(UInt32)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\014UInt32Protos'))
# @@protoc_insertion_point(module_scope)
