# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/user_cmd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import light_pb2 as ignition_dot_msgs_dot_light__pb2
from ignition.msgs import model_pb2 as ignition_dot_msgs_dot_model__pb2
from ignition.msgs import world_control_pb2 as ignition_dot_msgs_dot_world__control__pb2
from ignition.msgs import wrench_pb2 as ignition_dot_msgs_dot_wrench__pb2
from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/user_cmd.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1cignition/msgs/user_cmd.proto\x12\rignition.msgs\x1a\x19ignition/msgs/light.proto\x1a\x19ignition/msgs/model.proto\x1a!ignition/msgs/world_control.proto\x1a\x1aignition/msgs/wrench.proto\x1a\x1aignition/msgs/header.proto\"\xf6\x02\n\x07UserCmd\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12)\n\x04type\x18\x04 \x01(\x0e\x32\x1b.ignition.msgs.UserCmd.Type\x12#\n\x05model\x18\x05 \x03(\x0b\x32\x14.ignition.msgs.Model\x12#\n\x05light\x18\x06 \x03(\x0b\x32\x14.ignition.msgs.Light\x12\x13\n\x0b\x65ntity_name\x18\x07 \x01(\t\x12\x32\n\rworld_control\x18\x08 \x01(\x0b\x32\x1b.ignition.msgs.WorldControl\x12%\n\x06wrench\x18\t \x01(\x0b\x32\x15.ignition.msgs.Wrench\">\n\x04Type\x12\n\n\x06MOVING\x10\x00\x12\x11\n\rWORLD_CONTROL\x10\x01\x12\n\n\x06WRENCH\x10\x02\x12\x0b\n\x07SCALING\x10\x03\x42\"\n\x11\x63om.ignition.msgsB\rUserCmdProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_light__pb2.DESCRIPTOR,ignition_dot_msgs_dot_model__pb2.DESCRIPTOR,ignition_dot_msgs_dot_world__control__pb2.DESCRIPTOR,ignition_dot_msgs_dot_wrench__pb2.DESCRIPTOR,ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_USERCMD_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='ignition.msgs.UserCmd.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOVING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORLD_CONTROL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRENCH', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCALING', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=505,
  serialized_end=567,
)
_sym_db.RegisterEnumDescriptor(_USERCMD_TYPE)


_USERCMD = _descriptor.Descriptor(
  name='UserCmd',
  full_name='ignition.msgs.UserCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.UserCmd.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ignition.msgs.UserCmd.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='ignition.msgs.UserCmd.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ignition.msgs.UserCmd.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='ignition.msgs.UserCmd.model', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='light', full_name='ignition.msgs.UserCmd.light', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='ignition.msgs.UserCmd.entity_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world_control', full_name='ignition.msgs.UserCmd.world_control', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrench', full_name='ignition.msgs.UserCmd.wrench', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERCMD_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=567,
)

_USERCMD.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
_USERCMD.fields_by_name['type'].enum_type = _USERCMD_TYPE
_USERCMD.fields_by_name['model'].message_type = ignition_dot_msgs_dot_model__pb2._MODEL
_USERCMD.fields_by_name['light'].message_type = ignition_dot_msgs_dot_light__pb2._LIGHT
_USERCMD.fields_by_name['world_control'].message_type = ignition_dot_msgs_dot_world__control__pb2._WORLDCONTROL
_USERCMD.fields_by_name['wrench'].message_type = ignition_dot_msgs_dot_wrench__pb2._WRENCH
_USERCMD_TYPE.containing_type = _USERCMD
DESCRIPTOR.message_types_by_name['UserCmd'] = _USERCMD

UserCmd = _reflection.GeneratedProtocolMessageType('UserCmd', (_message.Message,), dict(
  DESCRIPTOR = _USERCMD,
  __module__ = 'ignition.msgs.user_cmd_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.UserCmd)
  ))
_sym_db.RegisterMessage(UserCmd)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\rUserCmdProtos'))
# @@protoc_insertion_point(module_scope)
