# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/wireless_node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/wireless_node.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n!ignition/msgs/wireless_node.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\"m\n\x0cWirelessNode\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\r\n\x05\x65ssid\x18\x02 \x01(\t\x12\x11\n\tfrequency\x18\x03 \x01(\x01\x12\x14\n\x0csignal_level\x18\x04 \x01(\x01\x42\'\n\x11\x63om.ignition.msgsB\x12WirelessNodeProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WIRELESSNODE = _descriptor.Descriptor(
  name='WirelessNode',
  full_name='ignition.msgs.WirelessNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.WirelessNode.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='essid', full_name='ignition.msgs.WirelessNode.essid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='ignition.msgs.WirelessNode.frequency', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal_level', full_name='ignition.msgs.WirelessNode.signal_level', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=189,
)

_WIRELESSNODE.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['WirelessNode'] = _WIRELESSNODE

WirelessNode = _reflection.GeneratedProtocolMessageType('WirelessNode', (_message.Message,), dict(
  DESCRIPTOR = _WIRELESSNODE,
  __module__ = 'ignition.msgs.wireless_node_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.WirelessNode)
  ))
_sym_db.RegisterMessage(WirelessNode)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\022WirelessNodeProtos'))
# @@protoc_insertion_point(module_scope)
