# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/world_reset.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ignition.msgs import header_pb2 as ignition_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ignition/msgs/world_reset.proto',
  package='ignition.msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x1fignition/msgs/world_reset.proto\x12\rignition.msgs\x1a\x1aignition/msgs/header.proto\"g\n\nWorldReset\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.ignition.msgs.Header\x12\x0b\n\x03\x61ll\x18\x02 \x01(\x08\x12\x11\n\ttime_only\x18\x03 \x01(\x08\x12\x12\n\nmodel_only\x18\x04 \x01(\x08\x42%\n\x11\x63om.ignition.msgsB\x10WorldResetProtosb\x06proto3')
  ,
  dependencies=[ignition_dot_msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WORLDRESET = _descriptor.Descriptor(
  name='WorldReset',
  full_name='ignition.msgs.WorldReset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ignition.msgs.WorldReset.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all', full_name='ignition.msgs.WorldReset.all', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_only', full_name='ignition.msgs.WorldReset.time_only', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_only', full_name='ignition.msgs.WorldReset.model_only', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=181,
)

_WORLDRESET.fields_by_name['header'].message_type = ignition_dot_msgs_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['WorldReset'] = _WORLDRESET

WorldReset = _reflection.GeneratedProtocolMessageType('WorldReset', (_message.Message,), dict(
  DESCRIPTOR = _WORLDRESET,
  __module__ = 'ignition.msgs.world_reset_pb2'
  # @@protoc_insertion_point(class_scope:ignition.msgs.WorldReset)
  ))
_sym_db.RegisterMessage(WorldReset)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.ignition.msgsB\020WorldResetProtos'))
# @@protoc_insertion_point(module_scope)
