name: osgar
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates=2017.4.17=0
- certifi=2017.4.17=py27_0
- jasper=1.900.1=4
- jpeg=9b=0
- libpng=1.6.28=0
- libtiff=4.0.6=7
- ncurses=5.9=10
- opencv=2.4.13=np113py27_1
- openssl=1.0.2k=0
- pip=9.0.1=py27_0
- python=2.7.13=1
- readline=6.2=0
- setuptools=33.1.1=py27_0
- sqlite=3.13.0=1
- tk=8.5.19=1
- wheel=0.29.0=py27_0
- xz=5.2.2=0
- zlib=1.2.11=0
- mkl=2017.0.1=0
- numpy=1.13.0=py27_0
- pip:
  - pygame==1.9.3
  - pyserial==3.3

