name: osgar
channels:
- conda-forge
- defaults
dependencies:
- certifi=2017.4.17=py27_0
- jpeg=9b=vc9_0
- libpng=1.6.28=vc9_0
- libtiff=4.0.6=vc9_7
- opencv=2.4.13=np113py27_1
- pip=9.0.1=py27_0
- python=2.7.13=1
- setuptools=33.1.1=py27_0
- vc=9=0
- wheel=0.29.0=py27_0
- wincertstore=0.2=py27_0
- zlib=1.2.11=vc9_0
- mkl=2017.0.1=0
- numpy=1.13.0=py27_0
- vs2008_runtime=9.00.30729.5054=0
- pip:
  - pygame==1.9.3
  - pyserial==3.3
